-- ============================================================================
-- Slice 3: Devices / Inventory / Charging
-- Source: docs/target/schema-postgres.md §7, docs/backend/domains/devices-charging.md
-- ADRs: 021, 024 (charging_timers merge, running_devices -> state),
--       025 (inventory_device_secrets split — A10)
--
-- Structure + RLS + the auth_owns_user_device() function. Data comes from the
-- ETL (Phase N+1). device_types was seeded in slice 2.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- containers  (shipping/batch grouping — Dealer scope resolves against .code)
-- ----------------------------------------------------------------------------
create table public.containers (
  id         bigint generated by default as identity primary key,
  code       text not null unique,        -- old `container_id`
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger containers_set_updated_at before update on public.containers
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- inventory_devices  (physical registry — secrets split out, A10)
-- ----------------------------------------------------------------------------
create table public.inventory_devices (
  id              bigint generated by default as identity primary key,
  name            text not null,
  description     text,
  activation_code text unique,
  dev_eui         text unique,
  container_id    bigint not null references public.containers (id) on delete cascade,
  product_id      bigint not null references public.products (id) on delete cascade,
  company_id      bigint references public.companies (id) on delete set null,
  xnid            text,                    -- old `xNID`
  t_code          text,
  serial_number   text,
  part_number     text,
  device_type_id  bigint references public.device_types (id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index inventory_devices_container_idx  on public.inventory_devices (container_id);
create index inventory_devices_product_idx    on public.inventory_devices (product_id);
create index inventory_devices_company_idx    on public.inventory_devices (company_id);
create index inventory_devices_device_type_idx on public.inventory_devices (device_type_id);
create trigger inventory_devices_set_updated_at before update on public.inventory_devices
  for each row execute function public.set_updated_at();

create table public.inventory_device_secrets (
  inventory_device_id bigint primary key references public.inventory_devices (id) on delete cascade,
  app_key  text,
  app_eui  text,   -- old `APPEUI`
  dev_addr text,   -- old `DEVADDR`
  nwkskey  text,   -- old `NWKSKEY`
  appskey  text,   -- old `APPSKEY`
  updated_at timestamptz not null default now()
);
create trigger inventory_device_secrets_set_updated_at before update on public.inventory_device_secrets
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- Placeholder for subscription_entitlements (built in slice 4) — user_devices
-- references it. Create a minimal stub now; slice 4 alters it.
-- ----------------------------------------------------------------------------
create table public.subscription_entitlements (
  id                       bigint generated by default as identity primary key,
  plan_id                  bigint references public.plans (id) on delete cascade,
  user_id                  uuid references public.profiles (id) on delete set null,
  owner_xnid               text,
  billing_xnid             text,
  dealer_xnid              text,
  billing_mode             public.billing_mode,
  source                   public.entitlement_source not null default 'system',
  payment_provider         public.payment_provider not null default 'stripe',
  provider_customer_id     text,
  provider_subscription_id text,
  max_devices_allowed      int,
  active_device_count      int not null default 0,
  status                   text not null default 'active',
  started_at               timestamptz,
  cancelled_at             timestamptz,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);
create index subscription_entitlements_owner_xnid_idx on public.subscription_entitlements (owner_xnid);
create trigger subscription_entitlements_set_updated_at before update on public.subscription_entitlements
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- user_devices  (a device claimed by an end user)
-- ----------------------------------------------------------------------------
create table public.user_devices (
  id                     bigint generated by default as identity primary key,
  dev_eui                text,
  xnid                   text,
  device_location        text,
  status                 public.user_device_status not null default 'decline',
  device_name            text,
  device_activation_code text,
  provider_subscription_id text,
  session_id             text,
  activation_status      text,
  activated_at           timestamptz,
  entitlement_id         bigint references public.subscription_entitlements (id) on delete set null,
  user_id                uuid not null references public.profiles (id) on delete cascade,
  package_id             bigint references public.packages (id) on delete set null,
  promo_code_id          bigint references public.promo_codes (id) on delete set null,
  inventory_device_id    bigint references public.inventory_devices (id) on delete cascade,
  -- current-state cache (replaces dev_val_last_packet / last_packet_json)
  last_reading           jsonb,
  last_reading_at        timestamptz,
  last_reading_id        bigint,
  last_dev_eui           text,
  notification_email     text,
  notification_phone_number text,
  toggle_status          boolean not null default true,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);
create index user_devices_user_idx      on public.user_devices (user_id);
create index user_devices_inventory_idx on public.user_devices (inventory_device_id);
create index user_devices_entitlement_idx on public.user_devices (entitlement_id);
create index user_devices_dev_eui_idx   on public.user_devices (dev_eui);
create index user_devices_session_idx   on public.user_devices (session_id);
create trigger user_devices_set_updated_at before update on public.user_devices
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- device_parameters  (per-device battery/charger config + protections)
-- ----------------------------------------------------------------------------
create table public.device_parameters (
  id                      bigint generated by default as identity primary key,
  dev_eui                 text unique,
  battery_voltage         int,
  battery_capacity        int,
  desired_charging        int,
  charging_limits         int,
  charger_voltage         int,
  charger_amperes         int,
  over_current_protection boolean not null default true,
  over_voltage_protection boolean not null default true,
  sms_alert               boolean not null default true,
  email_alert             boolean not null default true,
  is_default              boolean not null default false,
  user_id                 uuid references public.profiles (id) on delete cascade,
  user_device_id          bigint references public.user_devices (id) on delete cascade,
  inventory_device_id     bigint references public.inventory_devices (id) on delete cascade,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);
create trigger device_parameters_set_updated_at before update on public.device_parameters
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- device_schedules  (clock on/off)  +  sunset_rises  (astronomical)
-- ----------------------------------------------------------------------------
create table public.device_schedules (
  id             bigint generated by default as identity primary key,
  start_time     text not null,
  end_time       text not null,
  selected_days  jsonb not null,
  turn_on        boolean not null default true,
  reminder       boolean not null default false,
  user_device_id bigint references public.user_devices (id) on delete cascade,
  device_type_id bigint not null references public.device_types (id) on delete cascade,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create trigger device_schedules_set_updated_at before update on public.device_schedules
  for each row execute function public.set_updated_at();

create table public.sunset_rises (
  id             bigint generated by default as identity primary key,
  sunrise        int not null,           -- offset minutes
  sunset         int not null,
  selected_days  jsonb not null,
  turn_on        boolean not null,
  reminder       boolean not null default false,
  user_device_id bigint not null references public.user_devices (id) on delete cascade,
  device_type_id bigint not null references public.device_types (id) on delete cascade,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create trigger sunset_rises_set_updated_at before update on public.sunset_rises
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- charging_timers  (merged: charging_timers + quick_charging_timers — B11)
-- ----------------------------------------------------------------------------
create table public.charging_timers (
  id             bigint generated by default as identity primary key,
  kind           public.charging_timer_kind not null default 'standard',
  seconds        int,                    -- old `time` / `charging_time`
  is_active      boolean not null default false,
  user_id        uuid references public.profiles (id) on delete cascade,
  user_device_id bigint references public.user_devices (id) on delete cascade,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index charging_timers_user_device_idx on public.charging_timers (user_device_id);
create trigger charging_timers_set_updated_at before update on public.charging_timers
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- device_charging_state  (one row per user_device — from running_devices)
-- ----------------------------------------------------------------------------
create table public.device_charging_state (
  user_device_id      bigint primary key references public.user_devices (id) on delete cascade,
  dev_eui             text,
  is_on               boolean,
  is_charging         boolean not null default false,
  last_status         text,              -- old running_devices.status string
  last_command        text,
  last_command_at     timestamptz,
  user_id             uuid references public.profiles (id) on delete cascade,
  inventory_device_id bigint references public.inventory_devices (id) on delete cascade,
  updated_at          timestamptz not null default now()
);
create trigger device_charging_state_set_updated_at before update on public.device_charging_state
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- energy_usage_sessions  (was electric_energy_usages)
-- ----------------------------------------------------------------------------
create table public.energy_usage_sessions (
  id              bigint generated by default as identity primary key,
  dev_eui         text not null,
  user_device_id  bigint references public.user_devices (id) on delete cascade,
  energy_consumed numeric,
  status          text not null,          -- 'incomplete' | 'complete'
  counter         int,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index energy_usage_sessions_dev_eui_idx on public.energy_usage_sessions (dev_eui);
create trigger energy_usage_sessions_set_updated_at before update on public.energy_usage_sessions
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- device_health_schedulers
-- ----------------------------------------------------------------------------
create table public.device_health_schedulers (
  id               bigint generated by default as identity primary key,
  user_id          uuid not null references public.profiles (id) on delete cascade,
  schedule_title   text not null,
  time_zone        text not null,
  time             text not null,
  days             jsonb,
  selected_devices jsonb,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create trigger device_health_schedulers_set_updated_at before update on public.device_health_schedulers
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- device_assignments  (device <-> entitlement link)
-- ----------------------------------------------------------------------------
create table public.device_assignments (
  id                       bigint generated by default as identity primary key,
  xnid                     text not null,
  entitlement_id           bigint not null references public.subscription_entitlements (id) on delete cascade,
  provider_subscription_id text,
  status                   public.device_assignment_status not null default 'active',
  assigned_at              timestamptz not null default now(),
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  unique (xnid, entitlement_id)
);
create index device_assignments_entitlement_idx on public.device_assignments (entitlement_id);
create trigger device_assignments_set_updated_at before update on public.device_assignments
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- safeguard_configurations  (abnormal-alert throttling per device/user)
-- ----------------------------------------------------------------------------
create table public.safeguard_configurations (
  id                    bigint generated by default as identity primary key,
  user_id               uuid references public.profiles (id) on delete cascade,
  inventory_device_id   bigint references public.inventory_devices (id) on delete cascade,
  user_device_id        bigint references public.user_devices (id) on delete cascade,
  abnormal_alert_limit  int not null default 3,
  alert_interval_hours  numeric(5,2) not null default 24,
  support_email_sent    jsonb,
  support_number_sent   jsonb,
  is_active             boolean not null default true,      -- old globle_active_status '1'
  notifications_paused  boolean not null default false,     -- old globle_notifications_paused
  support_email_sent_at timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);
create trigger safeguard_configurations_set_updated_at before update on public.safeguard_configurations
  for each row execute function public.set_updated_at();

-- ============================================================================
-- auth_owns_user_device()  (auth-design.md §4 — the implicit per-role device
-- ownership from the old userLogin logic). Referenced by RLS on the device
-- tables and later `telemetry` / `alert_state`.
-- ============================================================================
create or replace function public.auth_owns_user_device(p_user_device bigint, p_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  with me as (
    select p.id, p.company_id, rt.title as role,
           coalesce(d.container_codes, '{}'::text[]) as container_codes,
           coalesce(d.inventory_device_ids, '{}'::bigint[]) as inventory_device_ids
    from public.profiles p
    join public.role_types rt on rt.id = p.role_type_id
    left join public.profile_details d on d.user_id = p.id
    where p.id = p_user
  ),
  ud as (
    select ud.user_id, ud.inventory_device_id, c.code as container_code
    from public.user_devices ud
    left join public.inventory_devices idv on idv.id = ud.inventory_device_id
    left join public.containers c on c.id = idv.container_id
    where ud.id = p_user_device
  )
  select case (select role from me)
    when 'Super Admin' then true
    when 'Customer'    then exists (select 1 from ud u where u.user_id = p_user)
    when 'Manager' then exists (
      select 1 from me m, ud u
      join public.profiles o on o.id = u.user_id
      where m.company_id is not null and o.company_id = m.company_id)
    when 'Admin' then exists (
      select 1 from me m, ud u
      join public.profiles o on o.id = u.user_id
      where m.company_id is not null and o.company_id = m.company_id)
    when 'Dealer' then exists (
      select 1 from me m, ud u
      where u.container_code = any (m.container_codes))
    when 'Partner' then exists (
      select 1 from me m, ud u
      where u.inventory_device_id = any (m.inventory_device_ids))
    else false
  end;
$$;

-- ============================================================================
-- RLS
-- ============================================================================
alter table public.containers               enable row level security;
alter table public.inventory_devices        enable row level security;
alter table public.inventory_device_secrets enable row level security;
alter table public.subscription_entitlements enable row level security;
alter table public.user_devices             enable row level security;
alter table public.device_parameters        enable row level security;
alter table public.device_schedules         enable row level security;
alter table public.sunset_rises             enable row level security;
alter table public.charging_timers          enable row level security;
alter table public.device_charging_state    enable row level security;
alter table public.energy_usage_sessions    enable row level security;
alter table public.device_health_schedulers enable row level security;
alter table public.device_assignments       enable row level security;
alter table public.safeguard_configurations enable row level security;

-- containers: readable by anyone with inventory access; writes with inventory
create policy containers_select on public.containers for select to authenticated
  using (public.auth_can('inventory', 'read') or public.auth_is_customer());
create policy containers_write on public.containers for all to authenticated
  using (public.auth_can('inventory', 'update')) with check (public.auth_can('inventory', 'create'));

-- inventory_devices: inventory scope + auth_scope_allows('inventory', id)
create policy inventory_devices_select on public.inventory_devices for select to authenticated
  using (
    public.auth_is_super_admin()
    or (public.auth_can('inventory', 'read') and public.auth_scope_allows('inventory', id))
    or (public.auth_is_customer() and exists (
          select 1 from public.user_devices ud
          where ud.inventory_device_id = inventory_devices.id
            and public.auth_owns_user_device(ud.id)))
  );
create policy inventory_devices_write on public.inventory_devices for all to authenticated
  using (public.auth_can('inventory', 'update') and public.auth_scope_allows('inventory', id))
  with check (public.auth_can('inventory', 'create'));

-- inventory_device_secrets: Super Admin or Admin-with-inventory-write only (A10 / ADR-025)
create policy inventory_device_secrets_select on public.inventory_device_secrets for select to authenticated
  using (
    public.auth_is_super_admin()
    or (public.auth_role_title() = 'Admin' and public.auth_can('inventory', 'update'))
  );
create policy inventory_device_secrets_write on public.inventory_device_secrets for all to authenticated
  using (public.auth_is_super_admin() or (public.auth_role_title() = 'Admin' and public.auth_can('inventory', 'update')))
  with check (public.auth_is_super_admin() or (public.auth_role_title() = 'Admin' and public.auth_can('inventory', 'update')));

-- subscription_entitlements: commerce read; writes via service role (Stripe/provisioning)
create policy subscription_entitlements_select on public.subscription_entitlements for select to authenticated
  using (public.auth_can('commerce', 'read') or user_id = auth.uid());
create policy subscription_entitlements_write on public.subscription_entitlements for all to authenticated
  using (public.auth_can('commerce', 'update')) with check (public.auth_can('commerce', 'create'));

-- user_devices: the implicit per-role ownership
create policy user_devices_select on public.user_devices for select to authenticated
  using (public.auth_owns_user_device(id));
create policy user_devices_write on public.user_devices for all to authenticated
  using (public.auth_owns_user_device(id))
  with check (
    user_id = auth.uid()
    or public.auth_can('inventory', 'update')
    or public.auth_is_super_admin()
  );

-- per-device config/state tables: gated by owning the user_device (or inventory perm)
do $$
declare t text;
begin
  foreach t in array array[
    'device_parameters','device_schedules','sunset_rises','charging_timers',
    'device_charging_state','energy_usage_sessions','safeguard_configurations'
  ]
  loop
    execute format($f$
      create policy %1$I on public.%2$I for all to authenticated
      using (
        public.auth_is_super_admin()
        or public.auth_can('inventory','update')
        or (%2$I.user_device_id is not null and public.auth_owns_user_device(%2$I.user_device_id))
      )
      with check (
        public.auth_is_super_admin()
        or public.auth_can('inventory','update')
        or (%2$I.user_device_id is not null and public.auth_owns_user_device(%2$I.user_device_id))
      )
    $f$, t || '_all', t);
  end loop;
end $$;

-- device_health_schedulers: a user manages their own (messaging,customer); managers via messaging
create policy device_health_schedulers_all on public.device_health_schedulers for all to authenticated
  using (user_id = auth.uid() or public.auth_can('messaging', 'update'))
  with check (user_id = auth.uid() or public.auth_can('messaging', 'update'));

-- device_assignments: commerce read; writes via service role
create policy device_assignments_select on public.device_assignments for select to authenticated
  using (public.auth_can('commerce', 'read') or public.auth_can('inventory', 'read'));
create policy device_assignments_write on public.device_assignments for all to authenticated
  using (public.auth_can('commerce', 'update')) with check (public.auth_can('commerce', 'create'));
