-- ============================================================================
-- Slice 7: Marina — physical layer (marinas / docks / slips / boats)
-- Source: docs/backend/domains/marina.md §A, docs/target/schema-postgres.md §11,
--         live ddev SHOW CREATE TABLE.
-- ADRs: 023 (marinas separate from buildings), 024 (boats + unassign_boats
--       merged — slip_id null = unassigned).
--
-- The PMS chain (rate_plans / quotes / reservations / …) is slice 8.
-- `slips.rate_plan_id` is a plain bigint here; slice 8 adds the FK.
-- Like slice 6, `slips` / `boats` carry a denormalised `marina_id` for the
-- `marina`-scope RLS and the dashboards.
-- ============================================================================

create table public.marinas (
  id                 bigint generated by default as identity primary key,
  marina_name        text,
  company_id         bigint references public.companies(id) on delete set null,  -- was varchar NOT NULL (B10)
  xnid               text,
  marina_code        text not null unique,
  location_code      text not null,
  county_code        text not null,
  marina_id          text not null,          -- telco code component
  city_code          text not null,
  on_net_type        text not null default '',
  structure_category text not null default '',
  map_rotation       numeric(10,2),
  zoom_level         numeric(10,2),
  structures         jsonb,
  uploaded_svg       text,
  occupancy_key      text,
  street_address     text,
  latitude           numeric(10,8),
  longitude          numeric(11,8),
  country            text,
  city               text,
  postal_code        text,
  state_province     text,
  noaa               text,
  clli_code          text,
  lata               text,
  npa                text,
  nxx                text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index marinas_company_idx on public.marinas (company_id);
create trigger marinas_set_updated_at before update on public.marinas
  for each row execute function public.set_updated_at();

create table public.docks (
  id            bigint generated by default as identity primary key,
  marina_id     bigint not null references public.marinas(id) on delete cascade,
  name          text not null,
  rotation      text,
  latitude      numeric(10,8),
  longitude     numeric(11,8),
  occupancy_key text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index docks_marina_idx on public.docks (marina_id);
create trigger docks_set_updated_at before update on public.docks
  for each row execute function public.set_updated_at();

create table public.slips (
  id               bigint generated by default as identity primary key,
  xnid             text,
  dock_id          bigint not null references public.docks(id) on delete cascade,
  marina_id        bigint not null references public.marinas(id) on delete cascade,
  name             text not null,
  slip_number      text,
  slip_code        text,
  slip_tier        text,
  slip_type        text,
  occupancy_status text,
  slip_status      text,
  rotation         text,
  notes            text,
  min_loa          int,
  max_loa          int,
  latitude         numeric(10,8),
  longitude        numeric(11,8),
  depth            int,
  rate_plan_id     bigint,                 -- FK added in slice 8 (rate_plans)
  is_active        boolean not null default true,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index slips_dock_idx   on public.slips (dock_id);
create index slips_marina_idx on public.slips (marina_id);
create trigger slips_set_updated_at before update on public.slips
  for each row execute function public.set_updated_at();

create table public.boats (
  id                bigint generated by default as identity primary key,
  xnid              text,
  storage_status    text default 'wet',
  marina_id         bigint not null references public.marinas(id) on delete cascade,
  dock_id           bigint references public.docks(id) on delete set null,
  slip_id           bigint references public.slips(id) on delete set null,
  user_id           uuid references public.profiles(id) on delete set null,  -- was varchar (B10)
  is_assigned       boolean generated always as (slip_id is not null) stored,

  boat_name         text not null,
  boat_model        text,
  boat_type         text,
  boat_length       text,
  boat_length_unit  text,
  boat_loa          text,
  boat_loa_unit     text default 'ft',
  beam              numeric(8,2),
  beam_unit         text,
  draft             numeric(8,2),
  draft_unit        text,
  power_requirement text,
  customer_type     text,

  street_address    text,
  latitude          numeric(10,8),
  longitude         numeric(11,8),
  country           text,
  state_province    text,
  city              text,
  postal_code       text,
  rotation          text,

  end_point         text,
  interface         text,
  accessory         text,
  clli_code         text,
  lata              text,
  npa               text,
  central_office_code text,
  nxx               text,
  noaa              text,
  market            text,

  monitoring_area   text,
  monitoring_room   text,
  monitoring_name   text,
  monitoring_opt_in text,

  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index boats_marina_idx on public.boats (marina_id);
create index boats_dock_idx   on public.boats (dock_id);
create index boats_slip_idx   on public.boats (slip_id);
create index boats_user_idx   on public.boats (user_id);
create index boats_unassigned_idx on public.boats (marina_id) where slip_id is null;
create trigger boats_set_updated_at before update on public.boats
  for each row execute function public.set_updated_at();

-- boats.inventory_device_id (JSON array) -> pivot (B10). A boat can carry
-- several monitoring devices.
create table public.boat_devices (
  boat_id             bigint not null references public.boats(id) on delete cascade,
  inventory_device_id bigint not null references public.inventory_devices(id) on delete cascade,
  created_at          timestamptz not null default now(),
  primary key (boat_id, inventory_device_id)
);
create index boat_devices_inventory_idx on public.boat_devices (inventory_device_id);

-- marina_alerts — the ProcessRealTimeAlert target (deferred from slice 5b).
-- Insert-only, Realtime-published, RLS-scoped per marina.
create table public.marina_alerts (
  id         bigint generated by default as identity primary key,
  marina_id  bigint not null references public.marinas(id) on delete cascade,
  boat_id    bigint references public.boats(id) on delete set null,
  payload    jsonb not null,
  created_at timestamptz not null default now()
);
create index marina_alerts_marina_time_idx on public.marina_alerts (marina_id, created_at desc);

-- ============================================================================
-- RLS — the `marina` data-scope entity + company
-- ============================================================================
alter table public.marinas      enable row level security;
alter table public.docks        enable row level security;
alter table public.slips        enable row level security;
alter table public.boats        enable row level security;
alter table public.boat_devices enable row level security;
alter table public.marina_alerts enable row level security;

create policy marinas_select on public.marinas for select to authenticated
  using (
    public.auth_is_super_admin()
    or (public.auth_can('marina', 'read') and public.auth_scope_allows('marina', id))
  );
create policy marinas_write on public.marinas for all to authenticated
  using (public.auth_can('marina', 'update') and public.auth_scope_allows('marina', id))
  with check (public.auth_can('marina', 'create'));

-- docks / slips: gated by the denormalised marina_id
do $$
declare t text;
begin
  foreach t in array array['docks','slips']
  loop
    execute format($f$
      create policy %1$I_select on public.%1$I for select to authenticated
      using (
        public.auth_is_super_admin()
        or (public.auth_can('marina','read') and public.auth_scope_allows('marina', marina_id))
      );
      create policy %1$I_write on public.%1$I for all to authenticated
      using (public.auth_can('marina','update') and public.auth_scope_allows('marina', marina_id))
      with check (public.auth_can('marina','create'));
    $f$, t);
  end loop;
end $$;

-- boats: marina scope, OR the boat's owner (a customer sees their own boat)
create policy boats_select on public.boats for select to authenticated
  using (
    public.auth_is_super_admin()
    or (public.auth_can('marina', 'read') and public.auth_scope_allows('marina', marina_id))
    or user_id = auth.uid()
  );
create policy boats_write on public.boats for all to authenticated
  using (public.auth_can('marina', 'update') and public.auth_scope_allows('marina', marina_id))
  with check (public.auth_can('marina', 'create'));

-- boat_devices: inherit the boat's visibility
create policy boat_devices_select on public.boat_devices for select to authenticated
  using (exists (
    select 1 from public.boats b
    where b.id = boat_devices.boat_id
      and (
        public.auth_is_super_admin()
        or (public.auth_can('marina','read') and public.auth_scope_allows('marina', b.marina_id))
        or b.user_id = auth.uid()
      )
  ));
create policy boat_devices_write on public.boat_devices for all to authenticated
  using (public.auth_can('marina', 'update')) with check (public.auth_can('marina', 'create'));

-- marina_alerts: read by marina scope; writes via service role (the alert engine)
create policy marina_alerts_select on public.marina_alerts for select to authenticated
  using (public.auth_is_super_admin() or public.auth_scope_allows('marina', marina_id));

alter publication supabase_realtime add table public.marina_alerts;
