-- ============================================================================
-- Slice 1: companies + domains (+ wiring profiles FKs, user_scopes ceiling)
-- Source: docs/target/schema-postgres.md §8, docs/target/auth-design.md §3/§6
-- ============================================================================

-- ----------------------------------------------------------------------------
-- companies  (old: companies — id / company_name / username / email unique)
-- ----------------------------------------------------------------------------
create table public.companies (
  id           bigint generated by default as identity primary key,
  company_name text not null,
  username     text not null,
  email        text not null unique,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create trigger companies_set_updated_at
  before update on public.companies
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- domains  (old: domains — id / domain_url). Tenancy is dormant in v1 (ADR-019)
-- but the table + the profiles/products domain_id columns are kept.
-- ----------------------------------------------------------------------------
create table public.domains (
  id         bigint generated by default as identity primary key,
  domain_url text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger domains_set_updated_at
  before update on public.domains
  for each row execute function public.set_updated_at();

-- The 7 dev-dump domains (representative — real values come from the ETL).
insert into public.domains (id, domain_url) values
  (1, 'https://devstage.assetgrid.example'),
  (2, 'https://app-devstage.assetgrid.example'),
  (3, 'https://aquagrid-devstage.assetgrid.example'),
  (4, 'https://sga-dev.assetgrid.example'),
  (5, 'http://localhost'),
  (6, 'http://127.0.0.1'),
  (7, 'https://assetgrid-battery.vercel.app');
select setval(pg_get_serial_sequence('public.domains', 'id'), 7, true);

-- ----------------------------------------------------------------------------
-- Wire the profiles FKs now that companies + domains exist.
-- ----------------------------------------------------------------------------
alter table public.profiles
  add constraint profiles_company_id_fkey
  foreign key (company_id) references public.companies (id) on delete set null;

alter table public.profiles
  add constraint profiles_domain_id_fkey
  foreign key (domain_id) references public.domains (id) on delete set null;

-- ----------------------------------------------------------------------------
-- RLS
-- ----------------------------------------------------------------------------
alter table public.companies enable row level security;
alter table public.domains   enable row level security;

-- companies: readable with commerce.read (or being a member); writes with commerce.*
create policy companies_select on public.companies for select
  using (
    public.auth_can('commerce', 'read')
    or id = (select company_id from public.profiles where id = auth.uid())
  );
create policy companies_insert on public.companies for insert
  with check (public.auth_can('commerce', 'create'));
create policy companies_update on public.companies for update
  using (public.auth_can('commerce', 'update'))
  with check (public.auth_can('commerce', 'update'));
create policy companies_delete on public.companies for delete
  using (public.auth_can('commerce', 'delete'));

-- domains: the login screen needs this list unauthenticated (old GET /api/domains
-- was guest). Public read; writes are super-admin only for now.
create policy domains_select on public.domains for select
  to anon, authenticated
  using (true);
create policy domains_write on public.domains for all
  to authenticated
  using (public.auth_is_super_admin())
  with check (public.auth_is_super_admin());

-- ----------------------------------------------------------------------------
-- user_scopes creator ceiling (auth-design.md §3): a non-Super-Admin may only
-- grant assets that they themselves can access. Enforced as a WITH CHECK that
-- every id in asset_ids passes auth_scope_allows for the *actor*.
-- ----------------------------------------------------------------------------
create or replace function public.auth_scope_grant_allowed(
  p_entity text,
  p_asset_ids bigint[],
  p_actor uuid default auth.uid()
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.auth_is_super_admin(p_actor)
    or not exists (
      select 1 from unnest(p_asset_ids) as a(id)
      where not public.auth_scope_allows(p_entity, a.id, p_actor)
    );
$$;

drop policy user_scopes_write on public.user_scopes;
create policy user_scopes_write on public.user_scopes for all
  using (public.auth_can('roles_permissions', 'update'))
  with check (
    public.auth_can('roles_permissions', 'create')
    and public.auth_scope_grant_allowed(entity_type, asset_ids)
  );
