-- ============================================================================
-- Slice 12: Twilio SMS groups + the messaging audit outbox
--   Source: TwilioController (1676 lines), schema-postgres.md §12.
--   - `sms_groups` / `sms_group_registers` / `sms_group_broadcast_messages`
--     (was `groups` / `group_registers` / `group_broadcast_messages`;
--     `admin_id`/`company_id`/`group_id` become real FKs, were varchar).
--   - `message_outbox` (ADR-036): every outbound SMS / email writes a row here.
--     When the provider is unconfigured (the normal state) the row is `mocked`
--     and nothing is actually sent — the user can see exactly what would go out.
-- RLS: `messaging` scope (perm + `auth_scope_allows('messaging', <group id>)`).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- sms_groups
-- ----------------------------------------------------------------------------
create table public.sms_groups (
  id                 bigint generated by default as identity primary key,
  group_name         text not null,
  admin_number       text,
  group_assigned_num text not null unique,
  topic              text,
  admin_id           uuid   references public.profiles(id)  on delete set null,
  company_id         bigint references public.companies(id) on delete set null,
  reg_id             text,                       -- legacy ':'-joined register id list (kept for parity)
  msg_id             text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index sms_groups_admin_idx on public.sms_groups (admin_id);
create index sms_groups_company_idx on public.sms_groups (company_id);
create trigger sms_groups_set_updated_at before update on public.sms_groups
  for each row execute function public.set_updated_at();

create table public.sms_group_registers (
  id         bigint generated by default as identity primary key,
  phone      text not null,
  group_id   bigint not null references public.sms_groups(id) on delete cascade,
  topic      text,
  created_at timestamptz not null default now(),
  unique (group_id, phone)
);
create index sms_group_registers_group_idx on public.sms_group_registers (group_id);

create table public.sms_group_broadcast_messages (
  id         bigint generated by default as identity primary key,
  group_id   bigint references public.sms_groups(id) on delete set null,  -- added (source had no FK)
  topic      text not null,
  message    text not null,
  phone      text not null,                      -- sender (admin or member)
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index sms_group_broadcast_messages_group_idx on public.sms_group_broadcast_messages (group_id);
create trigger sms_group_broadcast_messages_set_updated_at before update on public.sms_group_broadcast_messages
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- message_outbox  (ADR-036 — the "what would have been sent" audit)
-- ----------------------------------------------------------------------------
create table public.message_outbox (
  id          bigint generated by default as identity primary key,
  channel     text not null check (channel in ('sms', 'email')),
  to_address  text not null,
  from_address text,
  subject     text,
  body        text not null,
  context     jsonb,                             -- { source, group_id, alert_id, broadcast_id, … }
  status      text not null default 'mocked' check (status in ('mocked', 'sent', 'failed')),
  provider    text,                              -- 'twilio' | 'resend'
  provider_id text,
  error       text,
  created_at  timestamptz not null default now()
);
create index message_outbox_channel_idx on public.message_outbox (channel, created_at desc);
create index message_outbox_status_idx on public.message_outbox (status);
create index message_outbox_context_idx on public.message_outbox using gin (context);

-- ============================================================================
-- RLS
-- ============================================================================
alter table public.sms_groups                    enable row level security;
alter table public.sms_group_registers           enable row level security;
alter table public.sms_group_broadcast_messages  enable row level security;
alter table public.message_outbox                enable row level security;

-- sms_groups: messaging perm + data scope on the group id
create policy sms_groups_select on public.sms_groups for select to authenticated
  using (
    public.auth_is_super_admin()
    or (public.auth_can('messaging', 'read') and public.auth_scope_allows('messaging', id))
  );
create policy sms_groups_write on public.sms_groups for all to authenticated
  using (
    public.auth_is_super_admin()
    or (public.auth_can('messaging', 'update') and public.auth_scope_allows('messaging', id))
  )
  with check (
    public.auth_is_super_admin()
    or (public.auth_can('messaging', 'create')
        and (id is null or public.auth_scope_allows('messaging', id)))
  );

-- registers + broadcasts: scoped through their group_id
create policy sms_group_registers_select on public.sms_group_registers for select to authenticated
  using (
    public.auth_is_super_admin()
    or (public.auth_can('messaging', 'read') and public.auth_scope_allows('messaging', group_id))
  );
create policy sms_group_registers_write on public.sms_group_registers for all to authenticated
  using (public.auth_is_super_admin() or public.auth_can('messaging', 'update'))
  with check (public.auth_is_super_admin() or public.auth_can('messaging', 'create'));

create policy sms_group_broadcast_select on public.sms_group_broadcast_messages for select to authenticated
  using (
    public.auth_is_super_admin()
    or (public.auth_can('messaging', 'read')
        and (group_id is null or public.auth_scope_allows('messaging', group_id)))
  );
create policy sms_group_broadcast_write on public.sms_group_broadcast_messages for all to authenticated
  using (public.auth_is_super_admin() or public.auth_can('messaging', 'update'))
  with check (public.auth_is_super_admin() or public.auth_can('messaging', 'create'));

-- message_outbox: messaging read (or super admin); writes only via the
-- service-role client (the send helpers), same as the other system paths.
create policy message_outbox_select on public.message_outbox for select to authenticated
  using (public.auth_is_super_admin() or public.auth_can('messaging', 'read'));
