-- Auto-generated from the ddev backend (catalog reference data).
-- device_types, xups, notifies, apps, app_xup, attributes.

insert into public.device_types (id, name, description) values
  (1, 'AssetGridDuplex', 'Description for AssetGridDuplex'),
  (2, 'Grid Switch', 'Description for Grid Switch'),
  (3, 'AquaGrid One', 'Description for GridNotify'),
  (4, 'GridNotify HEAT', 'The GridNotify Heat* | wireless heat detection monitoring system. Provides 24/7 monitoring of external UL Heat sensor, temperature, humidity moiintoring'),
  (5, 'PWRNOTIFI', 'PWRNOTIFI'),
  (6, 'GRIDNOTIFY', 'GRIDNOTIFY'),
  (7, 'GENGRID', 'GENGRID'),
  (8, 'GridAC-R', 'GridAC-R'),
  (9, 'SGONEPIR', 'SGONEPIR'),
  (10, 'BILGEGRID ONE', 'AssetGrid BilgeGrid One™ | Wireless Boat Monitoring Kit.'),
  (11, 'BATTERY NOTIFI', 'BATTERY NOTIFI KIT - 12V/24V Adjustable Battery Monitoring Relay - NEMA Enclosure  Includes 10'' Fused Cable'),
  (12, 'GRID-SIBERIA', 'GridSiberia™ | Cold Chain Monitoring Sensor. Monitors temperature\nranges to -40C , constant temperature and humidity');
select setval(pg_get_serial_sequence('public.device_types','id'), (select max(id) from public.device_types));

insert into public.xups (id, code, data_type, version, description, format, units, label) values
  (1, '761', 'reed_state', '1', 'Contact Status', 'string/decimal', 'Boolean', ''),
  (2, '113', 'temperature', '0', 'Ambient temperature Fahrenheit', 'decimal', 'Fahrenheit (F)', ''),
  (3, '760', 'external_input', '1', 'Contact Status', 'string/decimal', 'Boolean', ''),
  (4, '205', 'humidity', '1', 'Ambient Humidity', 'decimal', 'Percentage (%)', ''),
  (5, '763', 'move', '1', 'Move', 'string/decimal', 'Boolean', null);
select setval(pg_get_serial_sequence('public.xups','id'), (select max(id) from public.xups));

insert into public.notifies (id, name) values
  (11, 'GridSiberia-NA'),
  (12, 'SG-ONE-AQU-NA'),
  (13, 'SG-ONE-BLG-NA-US'),
  (14, 'GENGRID ONE'),
  (15, 'GridNotify ONE'),
  (16, 'SG-ONE-MF-NA-HT-WH'),
  (17, 'POWER NOTIFY'),
  (18, 'SMARTGRID ONE'),
  (19, 'SMARTGRID ONE STORAGE'),
  (20, 'GRID AC/R'),
  (21, 'Battery Notifi Kit'),
  (22, 'BILGEGRID-ONE-Demo');
select setval(pg_get_serial_sequence('public.notifies','id'), (select max(id) from public.notifies));

insert into public.apps (id, app_name, optional_parameters, xup_id) values
  (1, 'SG-ONE-AQUA-NA', '"[1,2,3,4]"'::jsonb, null),
  (2, 'SG-ONE-BLG-NA-US', '"[2,4,3,1,5]"'::jsonb, null),
  (3, 'SG-ONE-GENGRID-NA', '"[1,2,3,4,5]"'::jsonb, null),
  (4, 'SG-ONE-NOTIFY-NA', '"[1,2,3,4]"'::jsonb, null),
  (5, 'SG-ONE-MF-NA-HT-WH', '"[1,2,3,4]"'::jsonb, null),
  (6, 'SG-ONE-PWRNTFY-NA', '"[2,3,4]"'::jsonb, null),
  (7, 'SG-ONE-MOTION-NA', '"[1,2,4,5]"'::jsonb, null),
  (8, 'SG-GRIDSIBERIA-NA', '"[2,4]"'::jsonb, null),
  (9, 'SG-ONE-GRID AC/R-NA', '"[2,3,4]"'::jsonb, null),
  (10, 'SG-ONE-BATTNOTFY-NA', '"[2,3,4]"'::jsonb, null);
select setval(pg_get_serial_sequence('public.apps','id'), (select max(id) from public.apps));

insert into public.app_xup (id, app_id, xup_id) values
  (9, 2, 2),
  (10, 2, 4),
  (11, 2, 3),
  (12, 2, 1),
  (13, 2, 5),
  (23, 5, 1),
  (24, 5, 2),
  (25, 5, 3),
  (26, 5, 4),
  (48, 6, 2),
  (49, 6, 3),
  (50, 6, 4),
  (51, 3, 1),
  (52, 3, 2),
  (53, 3, 3),
  (54, 3, 4),
  (55, 3, 5),
  (56, 4, 1),
  (57, 4, 2),
  (58, 4, 3),
  (59, 4, 4),
  (60, 7, 1),
  (61, 7, 2),
  (62, 7, 4),
  (63, 7, 5),
  (66, 8, 2),
  (67, 8, 4),
  (68, 9, 2),
  (69, 9, 3),
  (70, 9, 4),
  (71, 10, 2),
  (72, 10, 3),
  (73, 10, 4),
  (74, 1, 1),
  (75, 1, 2),
  (76, 1, 3),
  (77, 1, 4);
select setval(pg_get_serial_sequence('public.app_xup','id'), (select max(id) from public.app_xup));

insert into public.attributes (id, subject, alert_message, threshold, comparison, checkin, notifie_id, xup_id, description, alert_channel, neo_event_code) values
  (1, 'TEMPERATURE BELOW RANGE', 'GRID SIBERIA: $roomName - Temperature BELOW Range Battery:$voltage Signal:OK SITE GW: $roomName', '28', '<', false, 11, 2, 'Temperature', '0', null),
  (2, 'TEMPERATURE ABOVE RANGE', 'GRID SIBERIA: $roomName - Temperature ABOVE Range Battery:$voltage Signal:OK SITE GW: $roomName', '42', '>', false, 11, 2, 'Temperature', '0', null),
  (3, 'TEMPERATURE NORMAL', 'GRID SIBERIA: $roomName - Temperature Normal Battery:$voltage Signal:OK SITE GW: $roomName', '28-42', '-', true, 11, 2, 'Temperature', '0', null),
  (4, 'LEAK DETECTED', 'AssetGrid Alert: SmartGrid One-AQUA $roomName-LEAK DETECTED! Check NOW! Battery: $voltage Signal: OK', '1', '=', false, 12, 3, 'Water Leak', '0', 'WATER_LEAK'),
  (5, 'Water LEVEL NORMAL', 'AssetGrid Alert: SmartGrid One-AQUA $roomName-Water Level NORMAL Battery: $voltage Signal: OK', '0', '=', true, 12, 3, 'Water Leak', '0', 'WATER_LEAK'),
  (6, 'ALARM Closed', 'AssetGrid Alert: SmartGrid-Aqua $roomName - ALARM Closed! Normal Mode Battery: $voltage Signal: OK', '1', '=', true, 12, 1, 'Impact', '0', 'Tamper / Impact'),
  (7, 'Open ALARM detected', 'AssetGrid Alert: SmartGrid-Aqua $roomName - Open ALARM detected!   Battery: $voltage Signal: OK', '0', '=', false, 12, 1, 'Impact', '0', 'Tamper / Impact'),
  (8, 'High Water Detected', 'AssetGrid Alert: BILGEGRID ONE $roomName - High Water Alarm Detected! Check NOW! Battery: $voltage Signal: OK', '1', '=', false, 13, 3, 'Main Bilge Level', '0', 'WATER_LEAK'),
  (9, 'Water LEVEL NORMAL', 'AssetGrid Alert: BILGEGRID ONE $roomName -Water Level NORMAL Battery: $voltage Signal: OK', '0', '=', true, 13, 3, 'Main Bilge Level', '0', 'WATER_LEAK'),
  (10, 'ALARM Closed', 'AssetGrid Alert: BilgeGrid One $roomName - ALARM Closed! Normal Mode Battery: $voltage Signal: OK', '1', '=', true, 13, 1, 'Impact', '0', 'Tamper / Impact'),
  (11, 'Open ALARM detected', 'AssetGrid Alert: BilgeGrid One $roomName - Open ALARM detected! Battery: $voltage Signal: OK', '0', '=', false, 13, 1, 'Impact', '0', 'Tamper / Impact'),
  (12, 'Generator Running', 'AssetGrid Alert: GENGRID NOTIFY $roomName --Generator Running! Check NOW! Check NOW Battery:$voltage Signal:OK', '1', '=', false, 14, 3, 'Energy Usage', '0', null),
  (13, 'POWER Restored', 'AssetGrid Alert: PowerNotify $roomName -POWER Restored, In PROTECT MODE Battery:$voltage Signal:OK', '0', '=', true, 14, 3, 'Energy Usage', '0', null),
  (14, 'ALARM Closed', 'AssetGrid Alert: PowerNotify $roomName - ALARM Closed! Normal Mode Battery:$voltage Signal:OK', '1', '=', true, 14, 1, 'Impact', '0', null),
  (15, 'Open ALARM detected', 'AssetGrid Alert: PowerNotify $roomName - Open ALARM detected!   Battery:$voltage Signal:OK', '0', '=', false, 14, 1, 'Impact', '0', null),
  (16, 'ALARM DETECTED', 'AssetGrid Alert: SmartGrid-One $roomName -ALARM DETECTED! Check NOW Battery:$voltage Signal:OK', '1', '=', false, 15, 3, 'Water Leak', '0', '1'),
  (17, 'ALARM NORMAL', 'AssetGrid Alert: SmartGrid-One $roomName -ALARM NORMAL Battery:$voltage Signal:OK SITE GW: $roomName', '0', '=', true, 15, 3, 'Water Leak', '0', '1'),
  (18, 'ALARM Closed', 'AssetGrid Alert: SmartGrid-One $roomName - ALARM Closed! Normal Mode Battery:$voltage Signal:OK', '1', '=', true, 15, 1, 'Impact', '0', '1'),
  (19, 'Open ALARM detected', 'AssetGrid Alert: SmartGrid-One $roomName - Open ALARM detected! Battery:$voltage Signal:OK', '0', '=', false, 15, 1, 'Impact', '0', '1'),
  (20, 'GRID TEMP NOTIFY', 'AssetGrid Alert: GRID TEMP NOTIFY $roomName-HI HEAT DETECTED Check NOW! Battery: $voltage Signal: OK', '1', '=', false, 16, 3, 'Device Health', '0', '1'),
  (21, 'HEAT Normal', 'AssetGrid Alert: GRID TEMP NOTIFY $roomName-HEAT Normal, In PROTECT MODE Battery: $voltage Signal: OK', '0', '=', true, 16, 3, 'Device Health', '0', '1'),
  (22, 'ALARM Closed', 'AssetGrid Alert: GridTemp Notify $roomName - ALARM Closed! Normal Mode Battery:$voltage Signal:OK', '1', '=', true, 16, 1, 'Impact', '0', '1'),
  (23, 'Open ALARM detected', 'AssetGrid Alert: GridTemp Notify $roomName - Open ALARM detected! Battery:$voltage Signal:OK', '0', '=', false, 16, 1, 'Impact', '0', '1'),
  (24, 'POWER LOSS detected', 'AssetGrid Alert: PowerNotify $roomName. -POWER LOSS Detected! Check NOW! Battery: $voltage Signal: OK', '1', '=', false, 17, 3, 'Power', '0', 'AC_LOSS'),
  (25, 'POWER Restored', 'AssetGrid Alert: PowerNotify $roomName. -POWER Restored Battery: $voltage Signal: OK', '0', '=', true, 17, 3, 'Power', '0', 'AC_RESTORE'),
  (26, 'ALARM Closed', 'AssetGrid Alert: PowerNotify $roomName - ALARM Closed! Normal Mode Battery: $voltage Signal: OK', '1', '=', true, 17, 1, 'Impact', '0', 'Tamper / Impact'),
  (27, 'Open ALARM detected', 'AssetGrid Alert: PowerNotify $roomName - Open ALARM detected!   Battery: $voltage Signal: OK', '0', '=', false, 17, 1, 'Impact', '0', 'Tamper / Impact'),
  (28, 'MOTION DETECTED', 'AssetGrid Alert: SmartGrid ONE $roomName-Detected MOTION in Protected Area! Check NOW! Battery: $voltage Signal: OK', '1', '=', false, 18, 5, 'Motion', '0', 'CO'),
  (29, 'MOTION Normal', 'AssetGrid Alert: SmartGrid One $roomName-NORMAL in Protect Mode. Battery: $voltage Signal: OK', '0', '=', true, 18, 5, 'Motion', '0', 'CO'),
  (30, 'ALARM Closed', 'AssetGrid Alert: SmartGrid-One $roomName - ALARM Closed! Normal Mode Battery: $voltage Signal: OK', '1', '=', true, 18, 1, 'Impact', '0', 'Tamper / Impact'),
  (31, 'Open ALARM detected', 'AssetGrid Alert: SmartGrid-One $roomName - Open ALARM detected!   Battery: $voltage Signal: OK', '0', '=', false, 18, 1, 'Impact', '0', 'Tamper / Impact'),
  (32, 'LOW OIL detected', 'GRID AC/R: $roomName -LOW OIL detected! Check NOW! Battery:$voltage Signal:OK SITE GW: $roomName', '1', '=', false, 20, 3, 'Energy Usage', '0', null),
  (33, 'OIL LEVEL NORMAL', 'GRID AC/R: $roomName -OIL LEVEL NORMAL Battery:$voltage Signal:OK SITE GW: $roomName', '0', '=', true, 20, 3, 'Energy Usage', '0', null),
  (34, 'LOW BATTERY detected', 'AssetGrid Alert: Battery Notifi-$roomName -LOW BATTERY detected! Check NOW! Battery:$voltage Signal:OK', '0', '=', false, 21, 3, 'Battery', '0', '1'),
  (35, 'BATTERY Voltage Normal', 'AssetGrid Alert: Battery Notifi- $roomName -BATTERY Voltage Normal! Battery:$voltage Signal:OK', '1', '=', true, 21, 3, 'Battery', '0', '1'),
  (36, 'LOW BATTERY detected', 'AssetGrid Alert: Battery Notifi-$roomName -LOW BATTERY detected! Check NOW! Battery:$voltage Signal:OK', '1', '=', false, 22, 3, 'Device Health', '0', 'WATER_LEAK'),
  (37, 'BATTERY Voltage Normal', 'AssetGrid Alert: Battery Notifi- $roomName -BATTERY Voltage Normal! Battery:$voltage Signal:OK', '0', '=', true, 22, 3, 'Device Health', '0', 'GAS'),
  (38, 'High Water Detected', 'AssetGrid Alert: BILGEGRID ONE $roomName - High Water Alarm detected! Check NOW! Battery:$voltage Signal:OK', '1', '=', false, 22, 3, 'Main Bilge Level', '0', 'Tamper / Impact'),
  (39, 'Water Level Normal', 'AssetGrid Alert: BILGEGRID ONE $roomName -Water LEVEL NORMAL Battery:$voltage Signal:OK', '0', '=', true, 22, 3, 'Main Bilge Level', '0', 'Tamper / Impact'),
  (40, 'Security Normal', 'Security Normal', '1', '=', true, 22, 1, 'Security 1', '0', 'SMOKE'),
  (41, 'Security Alarm', 'Security Alarm', '0', '=', false, 22, 1, 'Security 1', '0', 'FIRE'),
  (42, 'TEMPERATURE ABOVE RANGE', 'GRID SIBERIA: $roomName - Temperature ABOVE Range Battery:$voltage Signal:OK SITE GW: $roomName', '42', '>', false, 22, 2, 'Temperature', '0', 'GAS'),
  (43, 'Alarm Closed', 'AssetGrid Alert: BilgeGrid One $roomName - ALARM Closed! Normal Mode Battery:$voltage Signal:OK', '1', '=', true, 22, 1, 'Impact', '0', 'FIRE'),
  (44, 'Open Alarm Detected', 'AssetGrid Alert: BilgeGrid One $roomName - Open ALARM detected! Battery:$voltage Signal:OK', '0', '=', false, 22, 1, 'Impact', '0', 'FIRE'),
  (45, 'Shore Power Alarm', 'Shore Power Alarm', '1', '=', false, 22, 3, 'Power', '0', 'FIRE'),
  (46, 'Shore Power NORMAL', 'Shore Power NORMAL', '0', '=', true, 22, 3, 'Power', '0', 'GAS'),
  (47, 'Battery Alarm', 'Battery Alarm', '1', '=', false, 22, 3, 'Battery', '0', 'GAS'),
  (48, 'Battery Normal', 'Battery Normal', '0', '=', true, 22, 3, 'Battery', '0', 'SMOKE'),
  (49, 'MOTION DETECTED', 'AssetGrid Alert: SmartGrid-One $roomName -detected MOTION in Protected Area! Check NOW! Battery:$voltage Signal:OK', '1', '=', false, 22, 5, 'Motion', '0', 'SMOKE'),
  (50, 'MOTION Normal', 'AssetGrid Alert: SmartGrid-One $roomName -NORMAL in Protect Mode. Battery:$voltage Signal:OK', '0', '=', true, 22, 5, 'Motion', '0', 'SMOKE'),
  (51, 'Energy Usage Alarm', 'Energy Usage Alarm', '1', '=', false, 22, 3, 'Energy Usage', '0', 'FIRE'),
  (52, 'Energy Usage Normal', 'Energy Usage Normal', '0', '=', true, 22, 3, 'Energy Usage', '0', 'GAS'),
  (53, 'TEMPERATURE BELOW RANGE', 'GRID SIBERIA: $roomName - Temperature BELOW Range Battery:$voltage Signal:OK SITE GW: $roomName', '28', '<', false, 22, 2, 'Temperature', '0', 'GAS'),
  (54, 'TEMPERATURE NORMAL', 'GRID SIBERIA: $roomName - Temperature Normal Battery:$voltage Signal:OK SITE GW: $roomName', '28-42', '-', true, 22, 2, 'Temperature', '0', 'FIRE'),
  (55, 'Water Leak', 'AquaGrid water leak', '1', '=', false, 22, 3, 'Water Leak', '0', null),
  (56, 'Water Normal', 'aquagrid Water Normal', '0', '=', true, 22, 3, 'Water Leak', '0', null),
  (57, 'ALARM Closed', 'AssetGrid Alert: Battery Notifi- $roomName - ALARM Closed! Normal Mode Battery: $voltage Signal: OK', '1', '=', true, 21, 1, 'Impact', '0', null),
  (58, 'Open ALARM detected', 'AssetGrid Alert: Battery Notifi- $roomName - Open ALARM detected! Battery: $voltage Signal: OK', '0', '=', false, 21, 1, 'Impact', '0', null);
select setval(pg_get_serial_sequence('public.attributes','id'), (select max(id) from public.attributes));

