-- ============================================================================
-- Slice 6: Buildings / Floors / Units / Areas / Sites
-- Source: docs/backend/domains/buildings.md, docs/target/schema-postgres.md §11,
--         live ddev SHOW CREATE TABLE.
-- ADRs: 023 (buildings vs marinas stay separate).
--
-- Deviation from source: `floors` / `units` / `areas` get a denormalised
-- `building_id` (the source only chains parent ids). It makes the `building`
-- scope RLS and the dashboard aggregation trivial; the hierarchy is write-rare.
-- ============================================================================

create table public.buildings (
  id                 bigint generated by default as identity primary key,
  company_id         bigint references public.companies(id) on delete cascade,
  location_code      text not null,
  county_code        text not null,
  building_id        text not null,          -- telco code component, NOT a self-ref
  city_code          text not null,
  building_code      text not null unique,
  on_net_type        text not null default '',
  structure_category text not null default '',
  street_address     text,
  latitude           numeric(10,8),
  longitude          numeric(11,8),
  country            text,
  city               text,
  postal_code        text,
  state_province     text,
  noaa               text,
  clli_code          text,
  lata               text,
  npa                text,
  nxx                text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index buildings_company_idx on public.buildings (company_id);
create trigger buildings_set_updated_at before update on public.buildings
  for each row execute function public.set_updated_at();

create table public.floors (
  id          bigint generated by default as identity primary key,
  building_id bigint not null references public.buildings(id) on delete cascade,
  name        text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index floors_building_idx on public.floors (building_id);
create trigger floors_set_updated_at before update on public.floors
  for each row execute function public.set_updated_at();

create table public.units (
  id          bigint generated by default as identity primary key,
  floor_id    bigint not null references public.floors(id) on delete cascade,
  building_id bigint not null references public.buildings(id) on delete cascade,
  name        text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index units_floor_idx on public.units (floor_id);
create index units_building_idx on public.units (building_id);
create trigger units_set_updated_at before update on public.units
  for each row execute function public.set_updated_at();

create table public.areas (
  id          bigint generated by default as identity primary key,
  unit_id     bigint not null references public.units(id) on delete cascade,
  building_id bigint not null references public.buildings(id) on delete cascade,
  name        text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index areas_unit_idx on public.areas (unit_id);
create index areas_building_idx on public.areas (building_id);
create trigger areas_set_updated_at before update on public.areas
  for each row execute function public.set_updated_at();

create table public.sites (
  id                  bigint generated by default as identity primary key,
  xnid                text,
  building_id         bigint not null references public.buildings(id) on delete cascade,
  area_id             bigint not null references public.areas(id) on delete cascade,
  user_id             uuid   references public.profiles(id) on delete set null,
  inventory_device_id bigint references public.inventory_devices(id) on delete set null,
  street_address      text,
  latitude            numeric(10,8),
  longitude           numeric(11,8),
  country             text,
  state_province      text,
  city                text,
  postal_code         text,
  room_name           text not null,
  end_point           text,
  interface           text,
  accessory           text,
  point               text not null default '0',
  unit_label          text,
  clli_code           text,
  lata                text,
  npa                 text,
  central_office_code text,
  nxx                 text,
  noaa                text,
  market              text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (inventory_device_id)
);
create index sites_building_idx  on public.sites (building_id);
create index sites_area_idx      on public.sites (area_id);
create index sites_user_idx      on public.sites (user_id);
create index sites_inventory_idx on public.sites (inventory_device_id);
create trigger sites_set_updated_at before update on public.sites
  for each row execute function public.set_updated_at();

-- The deferred FK from slice 5b (alert_windows.building_id was a plain bigint).
alter table public.alert_windows
  add constraint alert_windows_building_id_fkey
  foreign key (building_id) references public.buildings(id) on delete cascade;

-- ============================================================================
-- RLS — the `building` data-scope entity + company
-- ============================================================================
alter table public.buildings enable row level security;
alter table public.floors    enable row level security;
alter table public.units     enable row level security;
alter table public.areas     enable row level security;
alter table public.sites     enable row level security;

-- buildings: buildings-perm reader whose scope covers the building
create policy buildings_select on public.buildings for select to authenticated
  using (
    public.auth_is_super_admin()
    or (public.auth_can('buildings', 'read') and public.auth_scope_allows('building', id))
  );
create policy buildings_write on public.buildings for all to authenticated
  using (public.auth_can('buildings', 'update') and public.auth_scope_allows('building', id))
  with check (public.auth_can('buildings', 'create'));

-- floors / units / areas: gated by the denormalised building_id
do $$
declare t text;
begin
  foreach t in array array['floors','units','areas']
  loop
    execute format($f$
      create policy %1$I_select on public.%1$I for select to authenticated
      using (
        public.auth_is_super_admin()
        or (public.auth_can('buildings','read') and public.auth_scope_allows('building', building_id))
      );
      create policy %1$I_write on public.%1$I for all to authenticated
      using (public.auth_can('buildings','update') and public.auth_scope_allows('building', building_id))
      with check (public.auth_can('buildings','create'));
    $f$, t);
  end loop;
end $$;

-- sites: building scope, OR the device's owner (a customer sees their own site)
create policy sites_select on public.sites for select to authenticated
  using (
    public.auth_is_super_admin()
    or (public.auth_can('buildings', 'read') and public.auth_scope_allows('building', building_id))
    or user_id = auth.uid()
  );
create policy sites_write on public.sites for all to authenticated
  using (public.auth_can('buildings', 'update') and public.auth_scope_allows('building', building_id))
  with check (public.auth_can('buildings', 'create'));
