-- ============================================================================
-- Slice 5a: Telemetry ingestion core
-- Source: docs/target/schema-postgres.md §5/§6, docs/backend/06-webhooks-iot.md
-- ADRs: 022 (one partitioned telemetry table + last_reading cache on
--       user_devices), 005 (Mongo -> Postgres).
--
-- The `telemetry` table is designed for the FULL ~9.6M-row dataset; the ETL
-- (Phase N+1) loads only a recent slice into the free-tier budget (ADR-029).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- telemetry — range-partitioned monthly on created_at
-- ----------------------------------------------------------------------------
create table public.telemetry (
  id                  bigint generated by default as identity,
  created_at          timestamptz not null,
  updated_at          timestamptz not null default now(),

  dev_eui             text not null,                    -- uppercased on write
  gateway_id          text,
  user_id             uuid   references public.profiles(id)          on delete cascade,
  user_device_id      bigint references public.user_devices(id)      on delete cascade,
  inventory_device_id bigint references public.inventory_devices(id) on delete cascade,

  -- electrical (legacy AssetGrid charging devices) — numeric, never int
  energy_consumption_meter_consumed numeric,
  energy_consumption_meter_elapsed  numeric,
  active_power       numeric,
  apparent_power     numeric,
  reactive_power     numeric,
  power_factor       numeric,
  voltage            numeric,
  current            numeric,

  -- environmental
  humidity           numeric,
  temperature        numeric,
  luminosity         numeric,

  -- discrete sensor states
  external_input     boolean,
  light              boolean,
  move               boolean,
  reed_state         smallint,

  -- geo
  latitude           numeric(10,8),
  longitude          numeric(11,8),
  altitude           numeric(10,4),

  -- provenance / raw
  raw_body           jsonb,
  raw_packet         text,
  xup_encoded_edr    text,
  xup_decoded_edr    jsonb,
  legacy_id          bigint,
  legacy_mongo_id    text,
  raw_source         text not null default 'live'
    check (raw_source in ('live','mysql_device_values','mysql_device_values_dump','mongo_device_values')),

  primary key (id, created_at)
) partition by range (created_at);

create index telemetry_deveui_time_idx           on public.telemetry (dev_eui, created_at desc);
create index telemetry_userdevice_time_idx       on public.telemetry (user_device_id, created_at desc);
create index telemetry_inventorydevice_time_idx  on public.telemetry (inventory_device_id, created_at desc);
create index telemetry_legacy_mongo_id_idx       on public.telemetry (legacy_mongo_id) where legacy_mongo_id is not null;

-- Catch-all partition so an insert can never fail on a missing month.
create table public.telemetry_default partition of public.telemetry default;

-- Helper: create the monthly partition covering `p_month` (idempotent).
create or replace function public.create_telemetry_partition(p_month date)
returns void
language plpgsql
as $$
declare
  start_ts date := date_trunc('month', p_month)::date;
  end_ts   date := (date_trunc('month', p_month) + interval '1 month')::date;
  part     text := 'telemetry_' || to_char(start_ts, 'YYYY_MM');
begin
  if not exists (select 1 from pg_class where relname = part) then
    execute format(
      'create table public.%I partition of public.telemetry for values from (%L) to (%L)',
      part, start_ts, end_ts
    );
  end if;
end;
$$;

-- Seed partitions for the migratable window + a runway. The N+2 integrations
-- phase adds a pg_cron job that calls create_telemetry_partition() monthly.
do $$
declare m date;
begin
  for m in
    select generate_series('2024-01-01'::date, '2027-03-01'::date, interval '1 month')::date
  loop
    perform public.create_telemetry_partition(m);
  end loop;
end $$;

alter table public.telemetry enable row level security;

-- A subscriber / reader sees only telemetry for a device they own (the same
-- predicate the old app enforced implicitly). Writes are service-role only
-- (the webhook ingestion) — no write policy.
create policy telemetry_select on public.telemetry for select to authenticated
  using (
    public.auth_is_super_admin()
    or (user_device_id is not null and public.auth_owns_user_device(user_device_id))
    or (inventory_device_id is not null and public.auth_can('inventory', 'read')
        and public.auth_scope_allows('inventory', inventory_device_id))
  );

-- ----------------------------------------------------------------------------
-- neo_alarm_logs — the Neo central-station send log / retry queue
-- ----------------------------------------------------------------------------
create table public.neo_alarm_logs (
  id            bigint generated by default as identity primary key,
  telemetry_id  bigint,                          -- was Mongo _id varchar; not FK across partitions
  account_code  text not null,                   -- building/marina code
  point         int not null default 0,          -- unit/slip
  cid_code      text not null,
  event_code    text not null,
  cid_sent      boolean not null default false,
  cid_sent_at   timestamptz,
  cid_payload   text,
  uc_sent       boolean not null default false,
  uc_sent_at    timestamptz,
  uc_payload    jsonb,
  status        public.neo_alarm_status not null default 'pending',
  error_message text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index neo_alarm_logs_telemetry_idx     on public.neo_alarm_logs (telemetry_id);
create index neo_alarm_logs_account_point_idx on public.neo_alarm_logs (account_code, point);
create index neo_alarm_logs_status_idx        on public.neo_alarm_logs (status);
create index neo_alarm_logs_created_idx       on public.neo_alarm_logs (created_at);
create trigger neo_alarm_logs_set_updated_at before update on public.neo_alarm_logs
  for each row execute function public.set_updated_at();

alter table public.neo_alarm_logs enable row level security;
create policy neo_alarm_logs_select on public.neo_alarm_logs for select to authenticated
  using (public.auth_is_super_admin() or public.auth_can('marina', 'read') or public.auth_can('buildings', 'read'));

-- ----------------------------------------------------------------------------
-- Realtime: publish telemetry inserts (RLS-scoped per subscriber).
-- ----------------------------------------------------------------------------
alter publication supabase_realtime add table public.telemetry;
