-- ============================================================================
-- Slice 2: Catalog / config layer
-- Source: docs/target/schema-postgres.md §9, docs/backend/domains/catalog-billing.md
-- ADRs: 021 (int ids preserved), 024, 026
--
-- Structure only. Reference data (device_types, xups, notifies, apps, app_xup,
-- attributes) is seeded from a follow-up data migration generated off the ddev
-- backend. Business data (products, plans, vendors, packages, promo_codes) comes
-- from the ETL (Phase N+1) — the tables start empty.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- device_types  (12 rows — seeded next migration)
-- ----------------------------------------------------------------------------
create table public.device_types (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create trigger device_types_set_updated_at before update on public.device_types
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- xups  (numbered telemetry channel definitions — 5 rows)
-- ----------------------------------------------------------------------------
create table public.xups (
  id          bigint generated by default as identity primary key,
  code        text not null,             -- old `xUP` (e.g. "761")
  data_type   text not null,
  version     text not null,             -- old `xUPv`
  description text,
  format      text,
  units       text,
  label       text,                      -- fix of old `lable`
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create trigger xups_set_updated_at before update on public.xups
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- notifies  (product-line labels — 12 rows, ids 11-22 in the source)
-- ----------------------------------------------------------------------------
create table public.notifies (
  id         bigint generated by default as identity primary key,
  name       text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger notifies_set_updated_at before update on public.notifies
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- apps  (firmware application profiles)  +  app_xup pivot
-- ----------------------------------------------------------------------------
create table public.apps (
  id                  bigint generated by default as identity primary key,
  app_name            text not null,
  optional_parameters jsonb,
  xup_id              bigint references public.xups (id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index apps_xup_id_idx on public.apps (xup_id);
create trigger apps_set_updated_at before update on public.apps
  for each row execute function public.set_updated_at();

create table public.app_xup (
  id         bigint generated by default as identity primary key,
  app_id     bigint not null references public.apps (id) on delete cascade,
  xup_id     bigint not null references public.xups (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (app_id, xup_id)
);

-- ----------------------------------------------------------------------------
-- attributes  (system alert definitions — the alert engine reads these — 58 rows)
-- ----------------------------------------------------------------------------
create table public.attributes (
  id             bigint generated by default as identity primary key,
  subject        text not null,
  alert_message  text,
  threshold      text,
  comparison     text not null,          -- < > = -  ( "-" = "in range min-max" )
  checkin        boolean not null default false,   -- old varchar '0'/'1'
  notifie_id     bigint not null references public.notifies (id) on delete cascade,
  xup_id         bigint references public.xups (id) on delete set null,
  description    text,
  alert_channel  text not null default '0',
  neo_event_code text,                    -- old `is_event_code`
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index attributes_notifie_id_idx on public.attributes (notifie_id);
create index attributes_xup_id_idx on public.attributes (xup_id);
create trigger attributes_set_updated_at before update on public.attributes
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- vendors / packages / promo_codes  (referential only — no CRUD in the old app)
-- ----------------------------------------------------------------------------
create table public.vendors (
  id          bigint generated by default as identity primary key,
  name        text not null,
  address     text,
  description text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create trigger vendors_set_updated_at before update on public.vendors
  for each row execute function public.set_updated_at();

create table public.packages (
  id          bigint generated by default as identity primary key,
  name        text not null,
  price       numeric(12,2),             -- old varchar
  duration    text,
  description text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create trigger packages_set_updated_at before update on public.packages
  for each row execute function public.set_updated_at();

create table public.promo_codes (
  id          bigint generated by default as identity primary key,
  promo_code  text not null,
  description text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create trigger promo_codes_set_updated_at before update on public.promo_codes
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- plans  (subscription/activation plans — Stripe + Xero — soft delete)
-- ----------------------------------------------------------------------------
create table public.plans (
  id                    bigint generated by default as identity primary key,
  plan_code             text not null unique,
  name                  text not null,
  plan_family           text not null default 'consumer',
  tags                  text,
  device_limit          int not null default 1,      -- -1 = unlimited
  activation_type       text not null default 'Single',
  max_devices_per_batch int,
  requires_provisioning boolean not null default false,
  stripe_product_id     text,
  stripe_price_id       text,
  provisioning_price_id text,
  xero_revenue_code     text,
  xero_account_code     text,
  billing_modes         public.billing_mode[] not null default '{}',
  amount                numeric(12,2),
  billing_interval      text,
  billing_type          text not null default 'one_time',
  is_active             boolean not null default true,
  notes                 text,
  deleted_at            timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);
create index plans_plan_family_idx on public.plans (plan_family);
create index plans_stripe_price_id_idx on public.plans (stripe_price_id);
create trigger plans_set_updated_at before update on public.plans
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- products  (trimmed to the real columns — B14. ETL fills this.)
-- ----------------------------------------------------------------------------
create table public.products (
  id                  bigint generated by default as identity primary key,
  product_name        text,
  product_description text,
  model               text,
  sku                 text unique,
  price               numeric(12,2),
  status              boolean not null default false,
  device_id           text,
  image               text,
  sort_order          int,
  dimensions          jsonb,
  app_id              bigint references public.apps (id) on delete set null,
  notifie_id          bigint references public.notifies (id) on delete set null,
  company_id          bigint references public.companies (id) on delete cascade,
  domain_id           bigint references public.domains (id) on delete set null,
  device_type_id      bigint references public.device_types (id) on delete cascade,
  vendor_id           bigint references public.vendors (id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index products_company_id_idx on public.products (company_id);
create index products_device_type_id_idx on public.products (device_type_id);
create index products_notifie_id_idx on public.products (notifie_id);
create trigger products_set_updated_at before update on public.products
  for each row execute function public.set_updated_at();

create table public.product_plans (
  product_id bigint not null references public.products (id) on delete cascade,
  plan_id    bigint not null references public.plans (id) on delete cascade,
  primary key (product_id, plan_id)
);

-- ----------------------------------------------------------------------------
-- user_xup_preferences  (per-user visibility / notify toggles — real FKs now)
-- ----------------------------------------------------------------------------
create table public.user_xup_preferences (
  id                bigint generated by default as identity primary key,
  user_id           uuid not null references public.profiles (id) on delete cascade,
  product_id        bigint not null references public.products (id) on delete cascade,
  notifie_id        bigint references public.notifies (id) on delete set null,
  attribute_id      bigint references public.attributes (id) on delete set null,
  xup_id            bigint references public.xups (id) on delete set null,
  is_visible        boolean not null default true,
  send_notification boolean not null default true,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (user_id, product_id, notifie_id, attribute_id, xup_id)
);
create index user_xup_preferences_user_idx on public.user_xup_preferences (user_id);
create trigger user_xup_preferences_set_updated_at before update on public.user_xup_preferences
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- RLS
--   Catalog config (device_types/xups/apps/app_xup/notifies/attributes/vendors/
--   packages/promo_codes/products/product_plans/plans): readable by any
--   authenticated user (the app needs them widely — product pickers, the alert
--   config, activation UI). Writes gated by the owning module.
--   user_xup_preferences: a user manages their own; managers with catalog.
-- ----------------------------------------------------------------------------

create or replace function public.rls_catalog_read()
returns boolean language sql stable as $$ select auth.uid() is not null $$;

do $$
declare t text;
begin
  foreach t in array array[
    'device_types','xups','apps','app_xup','notifies','attributes',
    'vendors','packages','promo_codes','products','product_plans','plans'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format(
      'create policy %I on public.%I for select to authenticated using (true)',
      t || '_select', t);
  end loop;
end $$;

-- writes: catalog module
create policy attributes_write on public.attributes for all to authenticated
  using (public.auth_can('catalog','update')) with check (public.auth_can('catalog','create'));
create policy xups_write on public.xups for all to authenticated
  using (public.auth_can('catalog','update')) with check (public.auth_can('catalog','create'));
create policy apps_write on public.apps for all to authenticated
  using (public.auth_can('catalog','update')) with check (public.auth_can('catalog','create'));
create policy app_xup_write on public.app_xup for all to authenticated
  using (public.auth_can('catalog','update')) with check (public.auth_can('catalog','create'));
create policy products_write on public.products for all to authenticated
  using (public.auth_can('catalog','update')) with check (public.auth_can('catalog','create'));
create policy product_plans_write on public.product_plans for all to authenticated
  using (public.auth_can('catalog','update')) with check (public.auth_can('catalog','create'));
create policy device_types_write on public.device_types for all to authenticated
  using (public.auth_can('catalog','update') or public.auth_can('inventory','update'))
  with check (public.auth_can('catalog','create') or public.auth_can('inventory','create'));

-- writes: notifies — messaging module
create policy notifies_write on public.notifies for all to authenticated
  using (public.auth_can('messaging','update') or public.auth_is_customer())
  with check (public.auth_can('messaging','create') or public.auth_is_customer());

-- writes: plans — commerce module
create policy plans_write on public.plans for all to authenticated
  using (public.auth_can('commerce','update') or public.auth_is_customer())
  with check (public.auth_can('commerce','create') or public.auth_is_customer());

-- vendors/packages/promo_codes: super admin only (no real CRUD in the old app)
create policy vendors_write on public.vendors for all to authenticated
  using (public.auth_is_super_admin()) with check (public.auth_is_super_admin());
create policy packages_write on public.packages for all to authenticated
  using (public.auth_is_super_admin()) with check (public.auth_is_super_admin());
create policy promo_codes_write on public.promo_codes for all to authenticated
  using (public.auth_is_super_admin()) with check (public.auth_is_super_admin());

-- user_xup_preferences
alter table public.user_xup_preferences enable row level security;
create policy user_xup_prefs_select on public.user_xup_preferences for select
  using (user_id = auth.uid() or public.auth_can('catalog','read'));
create policy user_xup_prefs_write on public.user_xup_preferences for all
  using (user_id = auth.uid() or public.auth_can('catalog','update'))
  with check (user_id = auth.uid() or public.auth_can('catalog','update'));
