-- ============================================================================
-- Slice 4: Billing / Provisioning / Entitlements / Activation / Stripe
-- Source: docs/backend/domains/payments-provisioning.md,
--         docs/target/schema-postgres.md §10, live ddev SHOW CREATE TABLE.
-- ADRs: 021 (preserve bigint ids), 026 (money numeric(12,2)),
--       028 (envelope), A4 (keep Stripe sig verification).
--
-- `subscription_entitlements` + `device_assignments` were already created (full
-- shape) in the slice-3 devices migration — NOT re-created here. This migration
-- adds: activation_attempts, activation_attempt_devices, payments,
-- payment_details, stripe_events.
--
-- Row writes for all of these happen through the service-role client (the
-- Stripe webhook, checkout, provisioning) which bypasses RLS. The RLS policies
-- below only govern what an authenticated user can *read* + a `commerce`-write
-- fallback.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- activation_attempts  (one per checkout / dealer-activation attempt)
-- ----------------------------------------------------------------------------
create table public.activation_attempts (
  id                       bigint generated by default as identity primary key,
  session_id               text,
  idempotency_key          text unique,
  email                    text not null,
  user_id                  uuid references public.profiles (id) on delete set null,
  plan_id                  bigint not null references public.plans (id) on delete cascade,
  billing_mode             public.billing_mode not null,
  owner_xnid               text,
  billing_xnid             text,
  dealer_xnid              text,
  device_count             int not null,
  payment_provider         public.payment_provider not null default 'stripe',
  provider_reference_id    text,
  checkout_session_id      text,
  provider_customer_id     text,
  provider_subscription_id text,
  status                   public.activation_attempt_status not null default 'pending',
  completed_at             timestamptz,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);
create index activation_attempts_plan_idx           on public.activation_attempts (plan_id);
create index activation_attempts_user_idx           on public.activation_attempts (user_id);
create index activation_attempts_email_plan_status_idx
  on public.activation_attempts (email, plan_id, status, created_at);
create index activation_attempts_owner_xnid_idx     on public.activation_attempts (owner_xnid);
create index activation_attempts_billing_xnid_idx   on public.activation_attempts (billing_xnid);
create index activation_attempts_dealer_xnid_idx    on public.activation_attempts (dealer_xnid);
create index activation_attempts_checkout_session_idx on public.activation_attempts (checkout_session_id);
create index activation_attempts_provider_customer_idx on public.activation_attempts (provider_customer_id);
create index activation_attempts_provider_subscription_idx on public.activation_attempts (provider_subscription_id);
create trigger activation_attempts_set_updated_at before update on public.activation_attempts
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- activation_attempt_devices
-- ----------------------------------------------------------------------------
create table public.activation_attempt_devices (
  id                    bigint generated by default as identity primary key,
  activation_attempt_id bigint not null references public.activation_attempts (id) on delete cascade,
  xnid                  text not null,
  provider_status       text,
  provider_reference    text,
  validation_status     text not null default 'valid',   -- 'valid' | 'validated' | ...
  activation_status     text not null default 'pending',  -- 'pending' | 'activated' | ...
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  unique (activation_attempt_id, xnid)
);
create index activation_attempt_devices_attempt_status_idx
  on public.activation_attempt_devices (activation_attempt_id, activation_status);
create index activation_attempt_devices_xnid_idx on public.activation_attempt_devices (xnid);
create trigger activation_attempt_devices_set_updated_at before update on public.activation_attempt_devices
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- payments  (financial record — one per Stripe invoice / dealer activation)
-- ----------------------------------------------------------------------------
create table public.payments (
  id                  bigint generated by default as identity primary key,
  xnid                text,
  provider_invoice_id text unique,
  provider_payment_id text,
  payment_provider    public.payment_provider not null,
  payment_method      text,                       -- 'stripe' | 'dealer_billed' | 'cash' | ...
  amount              numeric(12,2) not null default 0,   -- B9/ADR-026: was decimal(10,2)
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index payments_xnid_idx           on public.payments (xnid);
create index payments_provider_payment_idx on public.payments (provider_payment_id);
create index payments_provider_idx       on public.payments (payment_provider);
create trigger payments_set_updated_at before update on public.payments
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- payment_details  (safe card metadata ONLY — last4/brand/expiry + billing addr)
-- The old `saveDevicePaymentDetail` tried to store raw card_number + CVV
-- (tech-debt A11) — NOT reproduced. This table is populated only from Stripe by
-- the webhook.
-- ----------------------------------------------------------------------------
create table public.payment_details (
  id         bigint generated by default as identity primary key,
  payment_id bigint not null references public.payments (id) on delete cascade,
  first_name text,
  last_name  text,
  card_last4 text,
  card_brand text,
  month      text,
  year       text,
  address_1  text,
  address_2  text,
  city       text,
  zip_code   text,
  state      text,
  country    text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (payment_id)
);
create trigger payment_details_set_updated_at before update on public.payment_details
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- stripe_events  (webhook idempotency — dedupe on event_id)
-- ----------------------------------------------------------------------------
create table public.stripe_events (
  id         bigint generated by default as identity primary key,
  event_id   text not null unique,
  type       text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger stripe_events_set_updated_at before update on public.stripe_events
  for each row execute function public.set_updated_at();

-- ============================================================================
-- RLS
-- ============================================================================
alter table public.activation_attempts        enable row level security;
alter table public.activation_attempt_devices enable row level security;
alter table public.payments                   enable row level security;
alter table public.payment_details            enable row level security;
alter table public.stripe_events              enable row level security;

-- activation_attempts: commerce readers, or the owner (their own attempt)
create policy activation_attempts_select on public.activation_attempts for select to authenticated
  using (public.auth_can('commerce', 'read') or user_id = auth.uid());
create policy activation_attempts_write on public.activation_attempts for all to authenticated
  using (public.auth_can('commerce', 'update')) with check (public.auth_can('commerce', 'create'));

-- activation_attempt_devices: inherit visibility from the parent attempt
create policy activation_attempt_devices_select on public.activation_attempt_devices for select to authenticated
  using (exists (
    select 1 from public.activation_attempts a
    where a.id = activation_attempt_devices.activation_attempt_id
      and (public.auth_can('commerce', 'read') or a.user_id = auth.uid())
  ));
create policy activation_attempt_devices_write on public.activation_attempt_devices for all to authenticated
  using (public.auth_can('commerce', 'update')) with check (public.auth_can('commerce', 'create'));

-- payments / payment_details: commerce readers only
create policy payments_select on public.payments for select to authenticated
  using (public.auth_can('commerce', 'read'));
create policy payments_write on public.payments for all to authenticated
  using (public.auth_can('commerce', 'update')) with check (public.auth_can('commerce', 'create'));

create policy payment_details_select on public.payment_details for select to authenticated
  using (public.auth_can('commerce', 'read'));
create policy payment_details_write on public.payment_details for all to authenticated
  using (public.auth_can('commerce', 'update')) with check (public.auth_can('commerce', 'create'));

-- stripe_events: Super Admin only (operational audit)
create policy stripe_events_select on public.stripe_events for select to authenticated
  using (public.auth_is_super_admin());
