-- ============================================================================
-- Slice 5b: Alerting engine tables
-- Source: docs/target/schema-postgres.md §3/§6,
--         docs/backend/06-webhooks-iot.md §4, notifications-rulebuilder.md
-- Consolidations (ADR-024): xup_notification_info -> alert_state,
--   notification_addresses -> device_notification_recipients.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- alert_state  (replaces xup_notification_info + the dead device_states shape)
-- one row per (user_device, attribute) — the alert/safeguard state machine.
-- ----------------------------------------------------------------------------
create table public.alert_state (
  id                    bigint generated by default as identity primary key,
  user_device_id        bigint not null references public.user_devices(id) on delete cascade,
  attribute_id          bigint references public.attributes(id) on delete cascade,
  dev_eui               text not null,
  product_id            bigint references public.products(id) on delete set null,
  notifie_id            bigint references public.notifies(id) on delete set null,
  inventory_device_id   bigint references public.inventory_devices(id) on delete cascade,

  value                 numeric,
  prev_value            numeric,
  is_alert              boolean not null default false,
  notification          text,               -- the xup data_type ("temperature", …)
  notification_type     text not null default 'normal',   -- 'normal' | 'alert'
  admin_bypass          boolean not null default false,   -- old active_status = 1

  alerts_count_24h      int not null default 0,
  window_started_at     timestamptz,
  last_alert_at         timestamptz,
  paused_until          timestamptz,
  notifications_paused  boolean not null default false,
  support_email_sent_at timestamptz,

  triggering_reading_id bigint,             -- telemetry(id); not FK across partitions
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  unique (user_device_id, attribute_id)
);
create index alert_state_deveui_idx on public.alert_state (dev_eui);
create index alert_state_inventory_idx on public.alert_state (inventory_device_id);
create trigger alert_state_set_updated_at before update on public.alert_state
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- alert_rules  (was customer_notifie_rules — the customer Rule Builder)
-- ----------------------------------------------------------------------------
create table public.alert_rules (
  id         bigint generated by default as identity primary key,
  title      text,
  is_active  boolean not null default true,      -- was `status`
  user_id    uuid not null references public.profiles(id) on delete cascade,
  devices    jsonb,        -- [{ product_id, user_device_id, inventory_device_id }]
  conditions jsonb,        -- [{ selectedAttribute, selectedCondition, conditionValue, logicalOperator }]
  notifie    text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index alert_rules_user_idx on public.alert_rules (user_id);
create trigger alert_rules_set_updated_at before update on public.alert_rules
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- alert_windows  (was notification_schedulers — quiet-hours / active-window)
-- building_id / marina_id stay plain bigint here; the FKs are added when the
-- buildings (slice 6) and marinas (slice 7) tables exist.
-- ----------------------------------------------------------------------------
create table public.alert_windows (
  id            bigint generated by default as identity primary key,
  rule_name     text,
  building_id   bigint,
  marina_id     bigint,
  company_id    bigint references public.companies(id) on delete set null,   -- was varchar (B10)
  attribute_key text not null,
  inventories   jsonb,      -- [{ value, label }] — inventory_device ids as strings
  days          text[],
  recurrence    public.scheduler_recurrence not null default 'weekly',
  start_time    time not null,
  end_time      time not null,
  timezone      text not null default 'UTC',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index alert_windows_attr_idx on public.alert_windows (attribute_key);
create trigger alert_windows_set_updated_at before update on public.alert_windows
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- notification_prefs  (was notifications — channel-config toggles)
-- ----------------------------------------------------------------------------
create table public.notification_prefs (
  id             bigint generated by default as identity primary key,
  user_id        uuid   references public.profiles(id) on delete cascade,
  user_device_id bigint references public.user_devices(id) on delete cascade,
  company_id     bigint references public.companies(id) on delete cascade,

  email_enabled            boolean not null default false,
  phone_enabled            boolean not null default false,
  customer_phone_enabled   boolean not null default false,
  customer_email_enabled   boolean not null default false,
  manager_phone_enabled    boolean not null default false,
  manager_email_enabled    boolean not null default false,
  device_phone_enabled     boolean not null default false,
  device_email_enabled     boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index notification_prefs_user_idx on public.notification_prefs (user_id);
create index notification_prefs_user_device_idx on public.notification_prefs (user_device_id);
create trigger notification_prefs_set_updated_at before update on public.notification_prefs
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- device_notification_recipients  (was notification_addresses — merged, arrays)
-- ----------------------------------------------------------------------------
create table public.device_notification_recipients (
  id             bigint generated by default as identity primary key,
  user_id        uuid   references public.profiles(id) on delete cascade,
  user_device_id bigint references public.user_devices(id) on delete cascade,
  emails         text[] not null default '{}',
  phone_numbers  text[] not null default '{}',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  unique (user_device_id)
);
create trigger device_notification_recipients_set_updated_at before update on public.device_notification_recipients
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- alert_log  (was notification_logs — audit of every alert email / SMS sent)
-- ----------------------------------------------------------------------------
create table public.alert_log (
  id             bigint generated by default as identity primary key,
  user_id        uuid   references public.profiles(id) on delete set null,
  telemetry_id   bigint,                     -- was device_value_id varchar
  device_name    text,
  user_device_id bigint references public.user_devices(id) on delete set null,
  channel        public.notification_channel not null,   -- was `type`
  recipient      text not null,
  message        text not null,
  subject        text,
  created_at     timestamptz not null default now()
);
create index alert_log_user_idx on public.alert_log (user_id);
create index alert_log_user_device_idx on public.alert_log (user_device_id);
create index alert_log_created_idx on public.alert_log (created_at);

-- ============================================================================
-- RLS
-- ============================================================================
alter table public.alert_state                    enable row level security;
alter table public.alert_rules                     enable row level security;
alter table public.alert_windows                   enable row level security;
alter table public.notification_prefs              enable row level security;
alter table public.device_notification_recipients  enable row level security;
alter table public.alert_log                       enable row level security;

-- alert_state: readable by the device owner or an inventory reader; writes via service role
create policy alert_state_select on public.alert_state for select to authenticated
  using (
    public.auth_is_super_admin()
    or public.auth_can('inventory', 'read')
    or public.auth_owns_user_device(user_device_id)
  );

-- alert_rules: a user owns their own rules; rulebuilder perm sees all
create policy alert_rules_select on public.alert_rules for select to authenticated
  using (user_id = auth.uid() or public.auth_can('rulebuilder', 'read'));
create policy alert_rules_write on public.alert_rules for all to authenticated
  using (user_id = auth.uid() or public.auth_can('rulebuilder', 'update'))
  with check (user_id = auth.uid() or public.auth_can('rulebuilder', 'create'));

-- alert_windows: rulebuilder module
create policy alert_windows_select on public.alert_windows for select to authenticated
  using (public.auth_can('rulebuilder', 'read'));
create policy alert_windows_write on public.alert_windows for all to authenticated
  using (public.auth_can('rulebuilder', 'update'))
  with check (public.auth_can('rulebuilder', 'create'));

-- notification_prefs: own rows, or messaging perm
create policy notification_prefs_all on public.notification_prefs for all to authenticated
  using (user_id = auth.uid() or public.auth_can('messaging', 'update'))
  with check (user_id = auth.uid() or public.auth_can('messaging', 'create'));

-- device_notification_recipients: own device, or inventory/messaging perm
create policy device_notification_recipients_all on public.device_notification_recipients for all to authenticated
  using (
    user_id = auth.uid()
    or (user_device_id is not null and public.auth_owns_user_device(user_device_id))
    or public.auth_can('inventory', 'update')
    or public.auth_can('messaging', 'update')
  )
  with check (
    user_id = auth.uid()
    or (user_device_id is not null and public.auth_owns_user_device(user_device_id))
    or public.auth_can('inventory', 'update')
    or public.auth_can('messaging', 'update')
  );

-- alert_log: own rows, or messaging read; writes via service role
create policy alert_log_select on public.alert_log for select to authenticated
  using (user_id = auth.uid() or public.auth_can('messaging', 'read') or public.auth_is_super_admin());

-- Realtime: publish alert_state changes (RLS-scoped per subscriber).
alter publication supabase_realtime add table public.alert_state;
