-- ============================================================================
-- Slice 8: Marina PMS chain
-- Source: docs/backend/domains/marina.md §B, docs/target/schema-postgres.md §11
--   "Marina PMS chain", live ddev SHOW CREATE TABLE, PricingService.
-- ADRs: 024 (pos_sales + pos_transactions merged), 026 (money numeric(12,2)).
--
-- Money is DOLLARS (confirmed from PricingService — decimal + round(x,2),
-- TAX_RATE 0.08). The old int(11) columns in quotes/reservations become
-- numeric(12,2). `discount_type` is a code ('percent'|'fixed'), modelled text.
-- Every PMS table carries a denormalised `marina_id` for the one-hop
-- `marina`-scope RLS (same pattern as slices 6/7).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- rate_plans  (+ the deferred slips.rate_plan_id FK from slice 7)
-- ----------------------------------------------------------------------------
create table public.rate_plans (
  id         bigint generated by default as identity primary key,
  name       text,
  calc_type  text,                       -- 'monthly' | 'nightly' | …
  rate       numeric(12,2),
  start_date date,
  end_date   date,
  type       public.rate_plan_type,      -- 'percent' | 'fixed'
  condition  jsonb,                       -- [{ loa_operator, loa_value_1, loa_value_2 }]
  loa_unit   text,
  value      numeric(12,4),
  marina_id  bigint not null references public.marinas(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index rate_plans_marina_idx on public.rate_plans (marina_id);
create trigger rate_plans_set_updated_at before update on public.rate_plans
  for each row execute function public.set_updated_at();

alter table public.slips
  add constraint slips_rate_plan_id_fkey
  foreign key (rate_plan_id) references public.rate_plans(id) on delete set null;

-- ----------------------------------------------------------------------------
-- reservations  (referenced by quotes.reservation_id — created first)
-- ----------------------------------------------------------------------------
create table public.reservations (
  id           bigint generated by default as identity primary key,
  xnid         text,
  marina_id    bigint references public.marinas(id) on delete cascade,
  user_id      uuid   references public.profiles(id) on delete set null,
  dock_id      bigint references public.docks(id) on delete set null,
  boat_id      bigint references public.boats(id) on delete set null,
  slip_id      bigint references public.slips(id) on delete set null,
  quote_id     bigint,                    -- FK added after quotes exists
  rate_plan_id bigint references public.rate_plans(id) on delete set null,
  loa          int,
  start_date   date,
  end_date     date,
  days         int,
  rate         numeric(12,2),
  subtotal     numeric(12,2) not null default 0,
  tax          numeric(12,2) not null default 0,
  total        numeric(12,2) not null default 0,
  status       text not null default 'draft',
  billed_by    text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index reservations_marina_idx on public.reservations (marina_id);
create index reservations_boat_idx on public.reservations (boat_id);
create index reservations_slip_idx on public.reservations (slip_id);
create index reservations_status_idx on public.reservations (status);
create trigger reservations_set_updated_at before update on public.reservations
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- quotes
-- ----------------------------------------------------------------------------
create table public.quotes (
  id              bigint generated by default as identity primary key,
  xnid            text,
  marina_id       bigint references public.marinas(id) on delete cascade,
  slip_id         bigint references public.slips(id) on delete set null,
  rate_plan_id    bigint not null references public.rate_plans(id) on delete cascade,
  reservation_id  bigint references public.reservations(id) on delete set null,
  loa             int,
  loa_unit        text,
  start_date      date,
  end_date        date,
  rate            numeric(12,2),
  total           numeric(12,2),
  discount        numeric(12,2),
  discount_type   text,                    -- 'percent' | 'fixed' — a code, not money
  surcharge       numeric(12,2),
  hold_expires_at timestamptz,
  status          text default 'draft',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index quotes_marina_idx on public.quotes (marina_id);
create index quotes_rate_plan_idx on public.quotes (rate_plan_id);
create index quotes_hold_idx on public.quotes (hold_expires_at) where hold_expires_at is not null;
create trigger quotes_set_updated_at before update on public.quotes
  for each row execute function public.set_updated_at();

alter table public.reservations
  add constraint reservations_quote_id_fkey
  foreign key (quote_id) references public.quotes(id) on delete set null;

-- ----------------------------------------------------------------------------
-- contracts (+ contract_amendments)
-- ----------------------------------------------------------------------------
create table public.contracts (
  id                   bigint generated by default as identity primary key,
  xnid                 text,
  marina_id            bigint references public.marinas(id) on delete cascade,
  slip_id              bigint not null references public.slips(id) on delete cascade,
  boat_id              bigint not null references public.boats(id) on delete cascade,
  rate_plan_id         bigint not null references public.rate_plans(id) on delete cascade,
  reservation_id       bigint references public.reservations(id) on delete set null,
  contract_type        text,
  monthly_rate         numeric(12,2) not null,
  status               public.contract_status not null default 'required',
  signed_at            timestamptz,
  original_contract_id bigint references public.contracts(id) on delete set null,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create index contracts_marina_idx on public.contracts (marina_id);
create index contracts_slip_idx on public.contracts (slip_id);
create index contracts_boat_idx on public.contracts (boat_id);
create index contracts_status_idx on public.contracts (status);
create trigger contracts_set_updated_at before update on public.contracts
  for each row execute function public.set_updated_at();

create table public.contract_amendments (
  id                  bigint generated by default as identity primary key,
  xnid                text,
  marina_id           bigint references public.marinas(id) on delete cascade,
  contract_id         bigint not null references public.contracts(id) on delete cascade,
  amendment_type      text not null,          -- rate_change | date_extension | slip_change | terms_change
  description         text,
  changed_fields      jsonb,
  original_amount     numeric(12,2),
  new_amount          numeric(12,2),
  original_start_date date,
  original_end_date   date,
  new_start_date      date,
  new_end_date        date,
  original_slip_id    bigint references public.slips(id) on delete set null,
  new_slip_id         bigint references public.slips(id) on delete set null,
  status              text not null default 'draft',
  signed_at           timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index contract_amendments_contract_idx on public.contract_amendments (contract_id);
create trigger contract_amendments_set_updated_at before update on public.contract_amendments
  for each row execute function public.set_updated_at();

-- Contract e-signature tokens (public signed-URL flow, replaces Laravel `signed`).
create table public.contract_sign_tokens (
  token       text primary key,
  contract_id bigint not null references public.contracts(id) on delete cascade,
  amendment_id bigint references public.contract_amendments(id) on delete cascade,
  expires_at  timestamptz not null,
  used_at     timestamptz,
  created_at  timestamptz not null default now()
);
create index contract_sign_tokens_contract_idx on public.contract_sign_tokens (contract_id);

-- ----------------------------------------------------------------------------
-- assignments -> stays
-- ----------------------------------------------------------------------------
create table public.assignments (
  id             bigint generated by default as identity primary key,
  xnid           text,
  marina_id      bigint references public.marinas(id) on delete cascade,
  reservation_id bigint not null references public.reservations(id) on delete cascade,
  boat_id        bigint not null references public.boats(id) on delete cascade,
  slip_id        bigint references public.slips(id) on delete set null,
  start_date     date not null,
  end_date       date,
  status         text not null default 'unassigned',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index assignments_marina_idx on public.assignments (marina_id);
create index assignments_reservation_idx on public.assignments (reservation_id);
create trigger assignments_set_updated_at before update on public.assignments
  for each row execute function public.set_updated_at();

create table public.stays (
  id                 bigint generated by default as identity primary key,
  xnid               text,
  marina_id          bigint references public.marinas(id) on delete cascade,
  assignment_id      bigint not null references public.assignments(id) on delete cascade,
  reservation_id     bigint not null references public.reservations(id) on delete cascade,
  boat_id            bigint not null references public.boats(id) on delete cascade,
  slip_id            bigint references public.slips(id) on delete set null,
  expected_arrival   date,
  actual_arrival     date,
  expected_departure date,
  actual_departure   date,
  status             text not null default 'expected',   -- was the 'null' string (B12)
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index stays_marina_idx on public.stays (marina_id);
create index stays_assignment_idx on public.stays (assignment_id);
create trigger stays_set_updated_at before update on public.stays
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- pos_transactions  (merged pos_sales + pos_transactions — all links nullable)
-- ----------------------------------------------------------------------------
create table public.pos_transactions (
  id               bigint generated by default as identity primary key,
  xnid             text,
  marina_id        bigint references public.marinas(id) on delete cascade,
  stay_id          bigint references public.stays(id) on delete set null,
  reservation_id   bigint references public.reservations(id) on delete set null,
  assignment_id    bigint references public.assignments(id) on delete set null,
  contract_id      bigint references public.contracts(id) on delete set null,
  boat_id          bigint references public.boats(id) on delete set null,
  slip_id          bigint references public.slips(id) on delete set null,
  service_category text,                    -- fuel | utility | service | adjustment | tax | misc
  service_name     text not null,
  amount           numeric(12,2) not null,
  type             public.pos_txn_type not null default 'charge',
  quantity         int not null default 1,
  unit_price       numeric(12,2),
  notes            text,
  created_by       uuid references public.profiles(id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index pos_transactions_marina_idx on public.pos_transactions (marina_id);
create index pos_transactions_stay_idx on public.pos_transactions (stay_id);
create index pos_transactions_reservation_idx on public.pos_transactions (reservation_id);
create index pos_transactions_boat_idx on public.pos_transactions (boat_id);
create trigger pos_transactions_set_updated_at before update on public.pos_transactions
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- invoices -> ledgers ; meters
-- ----------------------------------------------------------------------------
create table public.invoices (
  id             bigint generated by default as identity primary key,
  xnid           text,
  marina_id      bigint references public.marinas(id) on delete cascade,
  billable_type  text not null,             -- polymorphic (kept) …
  billable_id    bigint not null,
  contract_id    bigint references public.contracts(id) on delete set null,   -- … + explicit FKs (kept)
  reservation_id bigint references public.reservations(id) on delete set null,
  stay_id        bigint references public.stays(id) on delete set null,
  amount         numeric(12,2) not null,
  status         public.invoice_status not null default 'unpaid',
  paid_at        timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index invoices_marina_idx on public.invoices (marina_id);
create index invoices_billable_idx on public.invoices (billable_type, billable_id);
create index invoices_status_idx on public.invoices (status);
create trigger invoices_set_updated_at before update on public.invoices
  for each row execute function public.set_updated_at();

create table public.ledgers (
  id         bigint generated by default as identity primary key,
  xnid       text,
  marina_id  bigint references public.marinas(id) on delete cascade,
  invoice_id bigint references public.invoices(id) on delete set null,
  debit      numeric(12,2) not null default 0,
  credit     numeric(12,2) not null default 0,
  memo       text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index ledgers_marina_idx on public.ledgers (marina_id);
create index ledgers_invoice_idx on public.ledgers (invoice_id);
create trigger ledgers_set_updated_at before update on public.ledgers
  for each row execute function public.set_updated_at();

create table public.meters (
  id         bigint generated by default as identity primary key,
  xnid       text,
  marina_id  bigint references public.marinas(id) on delete cascade,
  slip_id    bigint not null references public.slips(id) on delete cascade,
  reading    numeric(12,2) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index meters_slip_idx on public.meters (slip_id);
create trigger meters_set_updated_at before update on public.meters
  for each row execute function public.set_updated_at();

-- ============================================================================
-- RLS — `marina` scope on the denormalised marina_id; writes need marina perm.
-- contract_sign_tokens: no policy (service-role only — the sign route uses it).
-- ============================================================================
do $$
declare t text;
begin
  foreach t in array array[
    'rate_plans','reservations','quotes','contracts','contract_amendments',
    'assignments','stays','pos_transactions','invoices','ledgers','meters'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format($f$
      create policy %1$I_select on public.%1$I for select to authenticated
      using (
        public.auth_is_super_admin()
        or (marina_id is null and public.auth_can('marina','read'))
        or (marina_id is not null and public.auth_can('marina','read')
            and public.auth_scope_allows('marina', marina_id))
      );
      create policy %1$I_write on public.%1$I for all to authenticated
      using (public.auth_can('marina','update'))
      with check (public.auth_can('marina','create'));
    $f$, t);
  end loop;
end $$;

alter table public.contract_sign_tokens enable row level security;
-- (no policies — only the service-role client touches it)
