-- Auto-generated from the ddev backend (catalog reference data).
-- device_types, xups, notifies, apps, app_xup, attributes.

insert into public.device_types (id, name, description) values
  (1, 'eMAXDuplex', 'Description for eMAXDuplex'),
  (2, 'MAX Switch', 'Description for MAX Switch'),
  (3, 'AQUAMAX One', 'Description for MAXNOTIFI'),
  (4, 'MAXNOTIFI HEAT', 'The MAXNOTIFI Heat* | wireless heat detection monitoring system. Provides 24/7 monitoring of external UL Heat sensor, temperature, humidity moiintoring'),
  (5, 'PWRNOTIFI', 'PWRNOTIFI'),
  (6, 'SMXNOTIFI', 'SMXNOTIFI'),
  (7, 'GENMAX', 'GENMAX'),
  (8, 'MAXAC-R', 'MAXAC-R'),
  (9, 'SMXONEPIR', 'SMXONEPIR'),
  (10, 'BILGEMAX ONE', 'ARMIT BilgeMAX One™ | Wireless Boat Monitoring Kit.'),
  (11, 'BATTERY NOTIFI', 'BATTERY NOTIFI KIT - 12V/24V Adjustable Battery Monitoring Relay - NEMA Enclosure  Includes 10'' Fused Cable'),
  (12, 'MAX-SIBERIA', 'MAXSIBERIA™ | Cold Chain Monitoring Sensor. Monitors temperature\nranges to -40C , constant temperature and humidity');
select setval(pg_get_serial_sequence('public.device_types','id'), (select max(id) from public.device_types));

insert into public.xups (id, code, data_type, version, description, format, units, label) values
  (1, '761', 'reed_state', '1', 'Contact Status', 'string/decimal', 'Boolean', ''),
  (2, '113', 'temperature', '0', 'Ambient temperature Fahrenheit', 'decimal', 'Fahrenheit (F)', ''),
  (3, '760', 'external_input', '1', 'Contact Status', 'string/decimal', 'Boolean', ''),
  (4, '205', 'humidity', '1', 'Ambient Humidity', 'decimal', 'Percentage (%)', ''),
  (5, '763', 'move', '1', 'Move', 'string/decimal', 'Boolean', null);
select setval(pg_get_serial_sequence('public.xups','id'), (select max(id) from public.xups));

insert into public.notifies (id, name) values
  (11, 'MAXSIBERIA-NA'),
  (12, 'SMX-ONE-AQU-NA'),
  (13, 'SMX-ONE-BLG-NA-US'),
  (14, 'GENMAX ONE'),
  (15, 'MAXNOTIFI ONE'),
  (16, 'SMX-ONE-MF-NA-HT-WH'),
  (17, 'POWER NOTIFI'),
  (18, 'SMARTMAX ONE'),
  (19, 'SMARTMAX ONE STORAGE'),
  (20, 'MAX AC/R'),
  (21, 'Battery Notifi Kit'),
  (22, 'BILGIMAX-ONE-Chirp');
select setval(pg_get_serial_sequence('public.notifies','id'), (select max(id) from public.notifies));

insert into public.apps (id, app_name, optional_parameters, xup_id) values
  (1, 'SMX-ONE-AQUA-NA', '"[1,2,3,4]"'::jsonb, null),
  (2, 'SMX-ONE-BLG-NA-US', '"[2,4,3,1,5]"'::jsonb, null),
  (3, 'SMX-ONE-GENMAX-NA', '"[1,2,3,4,5]"'::jsonb, null),
  (4, 'SMX-ONE-NOTIFI-NA', '"[1,2,3,4]"'::jsonb, null),
  (5, 'SMX-ONE-MF-NA-HT-WH', '"[1,2,3,4]"'::jsonb, null),
  (6, 'SMX-ONE-PWRNTFI-NA', '"[2,3,4]"'::jsonb, null),
  (7, 'SMX-ONE-MOTION-NA', '"[1,2,4,5]"'::jsonb, null),
  (8, 'SMX-MAXSIBERIA-NA', '"[2,4]"'::jsonb, null),
  (9, 'SMX-ONE-MAX AC/R-NA', '"[2,3,4]"'::jsonb, null),
  (10, 'SMX-ONE-BATTNOTFI-NA', '"[2,3,4]"'::jsonb, null);
select setval(pg_get_serial_sequence('public.apps','id'), (select max(id) from public.apps));

insert into public.app_xup (id, app_id, xup_id) values
  (9, 2, 2),
  (10, 2, 4),
  (11, 2, 3),
  (12, 2, 1),
  (13, 2, 5),
  (23, 5, 1),
  (24, 5, 2),
  (25, 5, 3),
  (26, 5, 4),
  (48, 6, 2),
  (49, 6, 3),
  (50, 6, 4),
  (51, 3, 1),
  (52, 3, 2),
  (53, 3, 3),
  (54, 3, 4),
  (55, 3, 5),
  (56, 4, 1),
  (57, 4, 2),
  (58, 4, 3),
  (59, 4, 4),
  (60, 7, 1),
  (61, 7, 2),
  (62, 7, 4),
  (63, 7, 5),
  (66, 8, 2),
  (67, 8, 4),
  (68, 9, 2),
  (69, 9, 3),
  (70, 9, 4),
  (71, 10, 2),
  (72, 10, 3),
  (73, 10, 4),
  (74, 1, 1),
  (75, 1, 2),
  (76, 1, 3),
  (77, 1, 4);
select setval(pg_get_serial_sequence('public.app_xup','id'), (select max(id) from public.app_xup));

insert into public.attributes (id, subject, alert_message, threshold, comparison, checkin, notifie_id, xup_id, description, alert_channel, neo_event_code) values
  (1, 'TEMPERATURE BELOW RANGE', 'MAX SIBERIA: $roomName - Temperature BELOW Range Battery:$voltage Signal:OK SITE GW: $roomName', '28', '<', false, 11, 2, 'Temperature', '0', null),
  (2, 'TEMPERATURE ABOVE RANGE', 'MAX SIBERIA: $roomName - Temperature ABOVE Range Battery:$voltage Signal:OK SITE GW: $roomName', '42', '>', false, 11, 2, 'Temperature', '0', null),
  (3, 'TEMPERATURE NORMAL', 'MAX SIBERIA: $roomName - Temperature Normal Battery:$voltage Signal:OK SITE GW: $roomName', '28-42', '-', true, 11, 2, 'Temperature', '0', null),
  (4, 'LEAK DETECTED', 'ARMIT Alert: SmartMAX One-AQUA $roomName-LEAK DETECTED! Check NOW! Battery: $voltage Signal: OK', '1', '=', false, 12, 3, 'Water Leak', '0', 'WATER_LEAK'),
  (5, 'Water LEVEL NORMAL', 'ARMIT Alert: SmartMAX One-AQUA $roomName-Water Level NORMAL Battery: $voltage Signal: OK', '0', '=', true, 12, 3, 'Water Leak', '0', 'WATER_LEAK'),
  (6, 'ALARM Closed', 'ARMIT Alert: SmartMAX-AQUA $roomName - ALARM Closed! Normal Mode Battery: $voltage Signal: OK', '1', '=', true, 12, 1, 'Impact', '0', 'Tamper / Impact'),
  (7, 'Open ALARM detected', 'ARMIT Alert: SmartMAX-AQUA $roomName - Open ALARM detected!   Battery: $voltage Signal: OK', '0', '=', false, 12, 1, 'Impact', '0', 'Tamper / Impact'),
  (8, 'High Water Detected', 'ARMIT Alert: BILGEMAX ONE $roomName - High Water Alarm Detected! Check NOW! Battery: $voltage Signal: OK', '1', '=', false, 13, 3, 'Main Bilge Level', '0', 'WATER_LEAK'),
  (9, 'Water LEVEL NORMAL', 'ARMIT Alert: BILGEMAX ONE $roomName -Water Level NORMAL Battery: $voltage Signal: OK', '0', '=', true, 13, 3, 'Main Bilge Level', '0', 'WATER_LEAK'),
  (10, 'ALARM Closed', 'ARMIT Alert: BILGEMAX One $roomName - ALARM Closed! Normal Mode Battery: $voltage Signal: OK', '1', '=', true, 13, 1, 'Impact', '0', 'Tamper / Impact'),
  (11, 'Open ALARM detected', 'ARMIT Alert: BILGEMAX One $roomName - Open ALARM detected! Battery: $voltage Signal: OK', '0', '=', false, 13, 1, 'Impact', '0', 'Tamper / Impact'),
  (12, 'Generator Running', 'ARMIT Alert: GENMAX NOTIFI $roomName --Generator Running! Check NOW! Check NOW Battery:$voltage Signal:OK', '1', '=', false, 14, 3, 'Energy Usage', '0', null),
  (13, 'POWER Restored', 'ARMIT Alert: PowerNOTIFI $roomName -POWER Restored, In PROTECT MODE Battery:$voltage Signal:OK', '0', '=', true, 14, 3, 'Energy Usage', '0', null),
  (14, 'ALARM Closed', 'ARMIT Alert: PowerNOTIFI $roomName - ALARM Closed! Normal Mode Battery:$voltage Signal:OK', '1', '=', true, 14, 1, 'Impact', '0', null),
  (15, 'Open ALARM detected', 'ARMIT Alert: PowerNOTIFI $roomName - Open ALARM detected!   Battery:$voltage Signal:OK', '0', '=', false, 14, 1, 'Impact', '0', null),
  (16, 'ALARM DETECTED', 'ARMIT Alert: SmartMAX-One $roomName -ALARM DETECTED! Check NOW Battery:$voltage Signal:OK', '1', '=', false, 15, 3, 'Water Leak', '0', '1'),
  (17, 'ALARM NORMAL', 'ARMIT Alert: SmartMAX-One $roomName -ALARM NORMAL Battery:$voltage Signal:OK SITE GW: $roomName', '0', '=', true, 15, 3, 'Water Leak', '0', '1'),
  (18, 'ALARM Closed', 'ARMIT Alert: SmartMAX-One $roomName - ALARM Closed! Normal Mode Battery:$voltage Signal:OK', '1', '=', true, 15, 1, 'Impact', '0', '1'),
  (19, 'Open ALARM detected', 'ARMIT Alert: SmartMAX-One $roomName - Open ALARM detected! Battery:$voltage Signal:OK', '0', '=', false, 15, 1, 'Impact', '0', '1'),
  (20, 'MAX TEMP NOTIFI', 'ARMIT Alert: MAX TEMP NOTIFI $roomName-HI HEAT DETECTED Check NOW! Battery: $voltage Signal: OK', '1', '=', false, 16, 3, 'Device Health', '0', '1'),
  (21, 'HEAT Normal', 'ARMIT Alert: MAX TEMP NOTIFI $roomName-HEAT Normal, In PROTECT MODE Battery: $voltage Signal: OK', '0', '=', true, 16, 3, 'Device Health', '0', '1'),
  (22, 'ALARM Closed', 'ARMIT Alert: MAXTemp NOTIFI $roomName - ALARM Closed! Normal Mode Battery:$voltage Signal:OK', '1', '=', true, 16, 1, 'Impact', '0', '1'),
  (23, 'Open ALARM detected', 'ARMIT Alert: MAXTemp NOTIFI $roomName - Open ALARM detected! Battery:$voltage Signal:OK', '0', '=', false, 16, 1, 'Impact', '0', '1'),
  (24, 'POWER LOSS detected', 'ARMIT Alert: PowerNOTIFI $roomName. -POWER LOSS Detected! Check NOW! Battery: $voltage Signal: OK', '1', '=', false, 17, 3, 'Power', '0', 'AC_LOSS'),
  (25, 'POWER Restored', 'ARMIT Alert: PowerNOTIFI $roomName. -POWER Restored Battery: $voltage Signal: OK', '0', '=', true, 17, 3, 'Power', '0', 'AC_RESTORE'),
  (26, 'ALARM Closed', 'ARMIT Alert: PowerNOTIFI $roomName - ALARM Closed! Normal Mode Battery: $voltage Signal: OK', '1', '=', true, 17, 1, 'Impact', '0', 'Tamper / Impact'),
  (27, 'Open ALARM detected', 'ARMIT Alert: PowerNOTIFI $roomName - Open ALARM detected!   Battery: $voltage Signal: OK', '0', '=', false, 17, 1, 'Impact', '0', 'Tamper / Impact'),
  (28, 'MOTION DETECTED', 'ARMIT Alert: SmartMAX ONE $roomName-Detected MOTION in Protected Area! Check NOW! Battery: $voltage Signal: OK', '1', '=', false, 18, 5, 'Motion', '0', 'CO'),
  (29, 'MOTION Normal', 'ARMIT Alert: SmartMAX One $roomName-NORMAL in Protect Mode. Battery: $voltage Signal: OK', '0', '=', true, 18, 5, 'Motion', '0', 'CO'),
  (30, 'ALARM Closed', 'ARMIT Alert: SmartMAX-One $roomName - ALARM Closed! Normal Mode Battery: $voltage Signal: OK', '1', '=', true, 18, 1, 'Impact', '0', 'Tamper / Impact'),
  (31, 'Open ALARM detected', 'ARMIT Alert: SmartMAX-One $roomName - Open ALARM detected!   Battery: $voltage Signal: OK', '0', '=', false, 18, 1, 'Impact', '0', 'Tamper / Impact'),
  (32, 'LOW OIL detected', 'MAX AC/R: $roomName -LOW OIL detected! Check NOW! Battery:$voltage Signal:OK SITE GW: $roomName', '1', '=', false, 20, 3, 'Energy Usage', '0', null),
  (33, 'OIL LEVEL NORMAL', 'MAX AC/R: $roomName -OIL LEVEL NORMAL Battery:$voltage Signal:OK SITE GW: $roomName', '0', '=', true, 20, 3, 'Energy Usage', '0', null),
  (34, 'LOW BATTERY detected', 'ARMIT Alert: Battery Notifi-$roomName -LOW BATTERY detected! Check NOW! Battery:$voltage Signal:OK', '0', '=', false, 21, 3, 'Battery', '0', '1'),
  (35, 'BATTERY Voltage Normal', 'ARMIT Alert: Battery Notifi- $roomName -BATTERY Voltage Normal! Battery:$voltage Signal:OK', '1', '=', true, 21, 3, 'Battery', '0', '1'),
  (36, 'LOW BATTERY detected', 'ARMIT Alert: Battery Notifi-$roomName -LOW BATTERY detected! Check NOW! Battery:$voltage Signal:OK', '1', '=', false, 22, 3, 'Device Health', '0', 'WATER_LEAK'),
  (37, 'BATTERY Voltage Normal', 'ARMIT Alert: Battery Notifi- $roomName -BATTERY Voltage Normal! Battery:$voltage Signal:OK', '0', '=', true, 22, 3, 'Device Health', '0', 'GAS'),
  (38, 'High Water Detected', 'ARMIT Alert: BILGEMAX ONE $roomName - High Water Alarm detected! Check NOW! Battery:$voltage Signal:OK', '1', '=', false, 22, 3, 'Main Bilge Level', '0', 'Tamper / Impact'),
  (39, 'Water Level Normal', 'ARMIT Alert: BILGEMAX ONE $roomName -Water LEVEL NORMAL Battery:$voltage Signal:OK', '0', '=', true, 22, 3, 'Main Bilge Level', '0', 'Tamper / Impact'),
  (40, 'Security Normal', 'Security Normal', '1', '=', true, 22, 1, 'Security 1', '0', 'SMOKE'),
  (41, 'Security Alarm', 'Security Alarm', '0', '=', false, 22, 1, 'Security 1', '0', 'FIRE'),
  (42, 'TEMPERATURE ABOVE RANGE', 'MAX SIBERIA: $roomName - Temperature ABOVE Range Battery:$voltage Signal:OK SITE GW: $roomName', '42', '>', false, 22, 2, 'Temperature', '0', 'GAS'),
  (43, 'Alarm Closed', 'ARMIT Alert: BILGEMAX One $roomName - ALARM Closed! Normal Mode Battery:$voltage Signal:OK', '1', '=', true, 22, 1, 'Impact', '0', 'FIRE'),
  (44, 'Open Alarm Detected', 'ARMIT Alert: BILGEMAX One $roomName - Open ALARM detected! Battery:$voltage Signal:OK', '0', '=', false, 22, 1, 'Impact', '0', 'FIRE'),
  (45, 'Shore Power Alarm', 'Shore Power Alarm', '1', '=', false, 22, 3, 'Power', '0', 'FIRE'),
  (46, 'Shore Power NORMAL', 'Shore Power NORMAL', '0', '=', true, 22, 3, 'Power', '0', 'GAS'),
  (47, 'Battery Alarm', 'Battery Alarm', '1', '=', false, 22, 3, 'Battery', '0', 'GAS'),
  (48, 'Battery Normal', 'Battery Normal', '0', '=', true, 22, 3, 'Battery', '0', 'SMOKE'),
  (49, 'MOTION DETECTED', 'ARMIT Alert: SmartMAX-One $roomName -detected MOTION in Protected Area! Check NOW! Battery:$voltage Signal:OK', '1', '=', false, 22, 5, 'Motion', '0', 'SMOKE'),
  (50, 'MOTION Normal', 'ARMIT Alert: SmartMAX-One $roomName -NORMAL in Protect Mode. Battery:$voltage Signal:OK', '0', '=', true, 22, 5, 'Motion', '0', 'SMOKE'),
  (51, 'Energy Usage Alarm', 'Energy Usage Alarm', '1', '=', false, 22, 3, 'Energy Usage', '0', 'FIRE'),
  (52, 'Energy Usage Normal', 'Energy Usage Normal', '0', '=', true, 22, 3, 'Energy Usage', '0', 'GAS'),
  (53, 'TEMPERATURE BELOW RANGE', 'MAX SIBERIA: $roomName - Temperature BELOW Range Battery:$voltage Signal:OK SITE GW: $roomName', '28', '<', false, 22, 2, 'Temperature', '0', 'GAS'),
  (54, 'TEMPERATURE NORMAL', 'MAX SIBERIA: $roomName - Temperature Normal Battery:$voltage Signal:OK SITE GW: $roomName', '28-42', '-', true, 22, 2, 'Temperature', '0', 'FIRE'),
  (55, 'Water Leak', 'Aquamax water leak', '1', '=', false, 22, 3, 'Water Leak', '0', null),
  (56, 'Water Normal', 'aquamax Water Normal', '0', '=', true, 22, 3, 'Water Leak', '0', null),
  (57, 'ALARM Closed', 'ARMIT Alert: Battery Notifi- $roomName - ALARM Closed! Normal Mode Battery: $voltage Signal: OK', '1', '=', true, 21, 1, 'Impact', '0', null),
  (58, 'Open ALARM detected', 'ARMIT Alert: Battery Notifi- $roomName - Open ALARM detected! Battery: $voltage Signal: OK', '0', '=', false, 21, 1, 'Impact', '0', null);
select setval(pg_get_serial_sequence('public.attributes','id'), (select max(id) from public.attributes));

